Range
cricut/FishyJoes pull request #106
Opened 2023-04-26 21:11 UTC by mstokercricut

2023-04-26 21:56 UTC, cobbal requested changes

2023-04-26 21:56 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedClosedRange.swift
> +        self.nodeName = "TODO:athing"
I'd prefer not to merge this

2023-04-26 21:56 UTC, cobbal commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/RangeTests.kt
> +import java.sql.Date
!

2023-05-02 23:54 UTC, cobbal requested changes

2023-05-02 23:54 UTC, cobbal commented on Sources/FishyJoesCSharpRuntime/GenericConverters.swift
> +}
nit: This is a strange mix of visibility modifiers. I would change the fileprivate ones to be just (defaultly) internal

2023-05-02 23:54 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedClosedRange.swift
> +        .generic(base: "ClosedRange", args: [bound.converterType])
This shouldn't be converterType

2023-05-02 23:54 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedRange.swift
> +        self.cSharpType = .named(package: "Cricut.FishyJoesRuntime", name: "OpenRange<\(bound.cSharpType.name)>")
half open, half closed... something seems wrong here. Why did this pass the tests?

2023-05-02 23:54 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedRange.swift
> +        self.jniType = .object("kotlin/ranges/ClosedRange")
As mentioned in person. We should make the `com.cricut.fishyjoesruntime.OpenEndRange` interface.

2023-05-02 23:54 UTC, cobbal commented on c-sharp-runtime/src/ClosedRange.cs
> +        {
mixed newline styles?

2023-05-03 20:44 UTC, mstokercricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedRange.swift
> +        self.cSharpType = .named(package: "Cricut.FishyJoesRuntime", name: "OpenRange<\(bound.cSharpType.name)>")
OpenEndRange is not available, so we have to use ClosedRange. :-(

2023-05-16 17:09 UTC, cobbal requested changes

2023-05-16 17:09 UTC, cobbal commented on Sources/FishyJoesCSharpRuntime/GenericConverters.swift
> +public struct CSharpSwiftClosedRange {
opinion: this is the exact same type as CSharpSwiftRange. I would just have 1 type and 1 setup method (similar to how arrays, sets, and dictionaries use the same type)

2023-05-16 17:09 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedRange.swift
> +        self.nodeName = "{ lowerBound: \(bound.nodeName), upperBound: \(bound.nodeName) }"
This node type can be freely passed to something expecting a closed range, which seems less than ideal

2023-05-16 17:09 UTC, cobbal commented on Sources/FishyJoesJavaRuntime/Utils.swift
> +    public let invalidRange: String
naming nit: I would call this "InvalidRangeError" and call the string "message"

2023-05-16 17:09 UTC, cobbal commented on Sources/FishyJoesNodeRuntime/Utils.swift
> +public struct RangeOutOfBoundsError: Error {
Should probably move this to the FishyJoesCommonRuntime and de-duplicate

2023-05-16 17:09 UTC, cobbal commented on c-sharp-runtime/src/Loader+Ranges.cs
> +    delegate CreatedRef SwiftClosedRangeLowerBoundGetter(UnownedRef obj, out CreatedRef exn);
again, same types as open range. I would de-duplicate

2023-05-16 17:09 UTC, cobbal commented on integration-tests/TestAPI-bindings/node-test/Primitives.test.ts
> +        expect(TestAPI.Primitives.maxInt).toEqual(0x7FFFFFFFFFFFFFFF);
```
$ node
Welcome to Node.js v18.12.1.
Type ".help" for more information.
> 0x7FFFFFFFFFFFFFFF.toString(16)
'8000000000000000'
```

2023-05-16 17:09 UTC, cobbal commented on kotlin-runtime/src/main/kotlin/com/cricut/fishyjoes/runtime/SwiftClosedRange.kt
> +data class SwiftClosedRange<T: Comparable<T>>(
This class should have documentation, especially since the constructor may throw

2023-05-16 17:09 UTC, cobbal commented on kotlin-runtime/src/main/kotlin/com/cricut/fishyjoes/runtime/SwiftClosedRange.kt
> +data class SwiftClosedRange<T: Comparable<T>>(
Also, should we validate lowerBound <= upperBound on element-wise construction?

2023-05-16 21:32 UTC, mstokercricut commented on Sources/FishyJoesCSharpRuntime/GenericConverters.swift
> +public struct CSharpSwiftClosedRange {
They each have their own list of interfaces, so merging them would require 2 collections of `CSharpSwiftRangeAndClosedRange`. This formulation seems more straightforward to me...

2023-05-16 23:13 UTC, cobbal approved these changes
Awesome. Ship it.

2023-05-17 02:42 UTC, merged