Bscothern/async
cricut/FishyJoes pull request #109
Opened 2023-05-16 22:27 UTC by bscothern-Cricut

2023-06-16 16:29 UTC, bscothern-Cricut commented on Sources/FishyJoesNodeRuntime/NodeReference.swift
> +//        precondition(ref.ptr == nil, "Node reference has not been deallocated before going out of scope")
What do we want to do in this case? Does it make sense to dispatch to the main thread and have it deallocate the reference since it has an environment?

2023-06-16 19:48 UTC, cobbal requested changes
Looks good

2023-06-16 19:48 UTC, cobbal commented on Sources/FishyJoesCore/Translators/NodeTranslate.swift
> +                                    fragment.output("throw error")
This throw feels like it duplicates the error. Can we get rid of it?

2023-06-16 19:48 UTC, cobbal commented on Sources/FishyJoesCore/Translators/NodeTranslate.swift
> +                                    fragment.output("try Self.mutateNode(mutatingSelf, this: env.this(), env: env)")
Since this is common with the catch block, maybe it can be de-duplicated and hoisted to the 'do' block

2023-06-16 19:48 UTC, cobbal commented on Sources/FishyJoesCore/Translators/NodeTranslate.swift
> +                                }
This could also be moved to the do block so that we could fall through from the catch block. Your preference

2023-06-16 19:48 UTC, cobbal commented on Sources/FishyJoesCore/Translators/NodeTranslate.swift
> +            let resolved = context.resolve(type: method.isAsync ? makeAsyncIfNeeded(parameter.type) : parameter.type, generics: exportAnnotation.genericOverrides)
It seems wrong to silently convert function arguments to async. Are you sure this is still needed?

2023-06-16 19:48 UTC, cobbal commented on Sources/FishyJoesNodeRuntime/NAPI.swift
> +    public typealias MainThreadCallback = napi_threadsafe_function_call_js
the main thread callback is a concern of how we're using NAPI, not of NAPI itself, so this typealias doesn't belong here

2023-06-16 19:48 UTC, cobbal commented on Sources/FishyJoesNodeRuntime/NodeFunction.swift
> +    }
Is this intended to be blank?

2023-06-16 19:48 UTC, cobbal commented on Sources/FishyJoesNodeRuntime/NodeFunction.swift
> +    public static func toNode(_ value: @escaping SwiftType, env: NAPI.Env) throws 	-> NAPI.Value {
whitespace

2023-06-16 19:48 UTC, cobbal commented on Sources/FishyJoesNodeRuntime/NodeReference.swift
> +//        precondition(ref.ptr == nil, "Node reference has not been deallocated before going out of scope")
Yes, that makes sense now that we have a good way to always get an environment

2023-06-16 19:48 UTC, cobbal commented on Sources/FishyJoesNodeRuntime/Utils.swift
> + public func callbackBody(
I don't like the name shadowing which can silently introduce an async context. Both this and rethrowToNode should have different names so that the typechecker isn't the only person who knows when an async scope is being introduced

2023-06-16 19:48 UTC, cobbal commented on Sources/FishyJoesNodeRuntime/Utils.swift
> + public func callbackBody(
Especially since the (node) type is different between the two, as one is a promise.

2023-06-16 19:48 UTC, cobbal commented on Sources/FishyJoesNodeRuntime/js/wasm-napi.js
> +      napi_create_threadsafe_function: this.wrap((envPtr, funcIdx, asyncResourceIdx, asyncResourceNameIdx, maxQueueSize, initialThreadCount, finalizeData, finalizeCallback, callJavascriptMainThreadCa
These should follow NAPI for naming, not main thread

2023-07-05 22:32 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/Translators/NodeTranslate.swift
> +                                    fragment.output("throw error")
Good catch

2023-07-05 22:35 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/Translators/NodeTranslate.swift
> +                                }
It can't do that because if the resolve throws then we can't call reject on the same `deferred`.

2023-07-05 22:47 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/Translators/NodeTranslate.swift
> +            let resolved = context.resolve(type: method.isAsync ? makeAsyncIfNeeded(parameter.type) : parameter.type, generics: exportAnnotation.genericOverrides)
Ya not needed anymore.

2023-07-05 22:57 UTC, bscothern-Cricut commented on Sources/FishyJoesNodeRuntime/js/wasm-napi.js
> +      napi_create_threadsafe_function: this.wrap((envPtr, funcIdx, asyncResourceIdx, asyncResourceNameIdx, maxQueueSize, initialThreadCount, finalizeData, finalizeCallback, callJavascriptMainThreadCa
Fixed.

2023-07-05 23:01 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/Translators/NodeTranslate.swift
> +                                    fragment.output("try Self.mutateNode(mutatingSelf, this: env.this(), env: env)")
It can't because it needs to be applied with either a reject or resolve of a promise which can't be hoisted up into the do block and fall through.

2023-07-07 17:26 UTC, cobbal requested changes
1 small, but important change needed

2023-07-07 17:26 UTC, cobbal commented on Sources/FishyJoesNodeRuntime/NodeReference.swift
> +            try? env.deleteReference(ref)
This should guard against nil, probably before jumping threads

2023-07-07 18:47 UTC, bscothern-Cricut commented on Sources/FishyJoesNodeRuntime/NodeReference.swift
> +            try? env.deleteReference(ref)
Good catch

2023-07-07 18:59 UTC, cobbal approved these changes

2023-07-07 19:03 UTC, merged