Attributed string
cricut/FishyJoes pull request #121
Opened 2023-08-09 15:49 UTC by mstokercricut

* Adds TypeScript support for AttributedString
* Adds a TypeScript runtime module
* Cleans up directory structure a bit

2023-08-09 23:48 UTC, cobbal requested changes

2023-08-09 23:48 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedAttributedString.swift
> +var TranslatedAttributedString = ExternalTranslatedType(
These should be lowercased

2023-08-09 23:48 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/TypeScriptAnnotations.swift
> -        fragment.output("export type SwiftRange<T> = { lowerBound: T, upperBoundExclusive: T };")
👍

2023-08-09 23:48 UTC, cobbal commented on Sources/FishyJoesExecute/NPMPackage.swift
> -        self.name = "@cricut/\(config.module.lowercased())-\(platform.platform.replacingOccurrences(of: "node-", with: ""))"
This will cause new packages to be published with a different name

2023-08-09 23:48 UTC, cobbal commented on Sources/FishyJoesNodeRuntime/AttributedString/AttributedString.Runs.Index+node.swift
> +                            let hashValue = 0//try env.this(converter: AttributedString.Runs.Index.self).hashValue
This worries me a little. When do you expect to fix it?

2023-08-09 23:48 UTC, cobbal commented on Sources/FishyJoesNodeRuntime/AttributedString/AttributedString.Runs.Run+node.swift
> +                            let hashValue = AttributedString("", attributes: try env.this(converter: AttributedString.Runs.Run.self).attributes).hashValue
Empty string doesn't work here, since all attributed empty strings are apparently equal to each other. Changing it to "x" seems to produce different hash values though

2023-08-09 23:48 UTC, cobbal commented on node-runtimes/fishyjoes-runtime-node-native-macos/Runtime.cjs.node
Commited binary

2023-08-09 23:48 UTC, cobbal commented on package-lock.json
> +}
Shouldn't be committed, doubly so at the root of the project

2023-08-10 21:00 UTC, mstokercricut commented on Sources/FishyJoesNodeRuntime/AttributedString/AttributedString.Runs.Run+node.swift
> +                            let hashValue = AttributedString("", attributes: try env.this(converter: AttributedString.Runs.Run.self).attributes).hashValue
Nice catch

2023-08-10 22:20 UTC, mstokercricut commented on Sources/FishyJoesNodeRuntime/AttributedString/AttributedString.Runs.Index+node.swift
> +                            let hashValue = 0//try env.this(converter: AttributedString.Runs.Index.self).hashValue
I've started computing a hash value based on the content of the indices. hashValue is coming in Swift 5.9, but is not here yet...

2023-08-11 01:02 UTC, mstokercricut commented on Sources/FishyJoesExecute/NPMPackage.swift
> -        self.name = "@cricut/\(config.module.lowercased())-\(platform.platform.replacingOccurrences(of: "node-", with: ""))"
Hopefully I resolved this. We still need to figure out how file dependencies will work in CI and publish a real runtime package.

2023-08-11 20:26 UTC, cobbal approved these changes

2023-08-11 21:30 UTC, cobbal commented on Sources/FishyJoesExecute/NPMPackage.swift
> +
I don't like having a function and a variable with the same name. Makes referring to them difficult

2023-08-11 21:30 UTC, cobbal commented on scripts/compile-node-runtime.sh
> +        popd
Stray popd? I strongly prefer not to use pushd/popd for reasons like this. Open a new subshell and just "cd"

2023-08-11 21:30 UTC, cobbal commented on scripts/compile-node-runtime.sh
> +        popd
Or better yet, just change it to `ln -s Runtime.cjs.node node-runtime/fishyjoes-runtime-native-windows/libFishyJoesNodeRuntime.dll`

2023-08-14 23:54 UTC, merged