C# + Some Node.js Multi-Module Work
cricut/FishyJoes pull request #123
Opened 2023-08-15 00:38 UTC by mstokercricut

2023-08-21 19:54 UTC, cobbal requested changes

2023-08-21 19:54 UTC, cobbal commented on .github/workflows/c-sharp-runtime.yaml
> -    name: "linux: Build and test C# runtime"
If you must make all these changes to CI, be sure to do it to the templates in `Sources/FishyJoesExecute/Resources/bindings-template/.github/workflows` as well

2023-08-21 19:54 UTC, cobbal commented on .github/workflows/integration-tests.yaml
> +      - name: Test .NET
"dotnet" is the name of the executable loading the library. Very analogous to "node"

2023-08-21 19:54 UTC, cobbal commented on .github/workflows/integration-tests.yaml
> +      - name: Test Kotlin
The "from" parts are very important, because sometimes we test from swift test and sometimes we test from the foreign languages test framework.

2023-08-21 19:54 UTC, cobbal commented on .github/workflows/integration-tests.yaml
> +          run: /work/scripts/compile-android-runtime.sh
We should be pulling the compiled version from the previous run, not re-building

2023-08-21 19:54 UTC, cobbal commented on .github/workflows/integration-tests.yaml
> +      - name: Test Android
We're testing from the app specifically.

2023-08-21 19:54 UTC, cobbal commented on .github/workflows/java-runtime.yaml
> +          CONFIGURATION=debug ./scripts/compile-kotlin-native-runtime.sh
We should not be shipping debug builds

2023-08-21 19:54 UTC, cobbal commented on Sources/FishyJoesCSharpRuntime/AttributedString/AttributeContainer+cSharp.swift
> +                    mergePolicy: !Bool.peekCSharp(keepCurrent) ? .keepNew : .keepCurrent
nit: confusing needless negation

2023-08-21 19:54 UTC, cobbal commented on Sources/FishyJoesCSharpRuntime/AttributedString/AttributedString.Runs+cSharp.swift
> +            .map { AttributedString("HASH", attributes: $0.attributes).hashValue }
Is this ignoring the string component?

2023-08-21 19:54 UTC, cobbal commented on Sources/FishyJoesCSharpRuntime/AttributedString/AttributedString.Runs.Run+cSharp.swift
> +            Int32(truncatingIfNeeded: AttributedString("HASH", attributes: AttributedString.Runs.Run.peekCSharp(this).attributes).hashValue)
and here

2023-08-21 19:54 UTC, cobbal commented on Sources/FishyJoesCSharpRuntime/Env.swift
> +            print(message)
Probably shouldn't be an array anymore if only 1 line

2023-08-21 19:54 UTC, cobbal commented on scripts/compile-c-sharp-runtime.sh
> +function install-lib () {
style: Prefer function variable passing (referring to $1 and $2 inside the function) to pass-by-global-variable

2023-08-21 19:54 UTC, cobbal commented on scripts/compile-c-sharp-runtime.sh
> +install-lib
You've changed behavior here. Previously, at least 1 install had to succeed for the script to succeed. Now if all fail, the script still succeeds.

2023-08-21 19:55 UTC, cobbal commented on scripts/compile-c-sharp-runtime.sh
> +install-lib
(I suggest keeping the `||`s, but using them between the function invocations)

2023-08-21 20:44 UTC, mstokercricut commented on scripts/compile-c-sharp-runtime.sh
> +install-lib
👍🏿

2023-08-21 20:45 UTC, mstokercricut commented on Sources/FishyJoesCSharpRuntime/AttributedString/AttributedString.Runs+cSharp.swift
> +            .map { AttributedString("HASH", attributes: $0.attributes).hashValue }
Not sure. You mentioned that all empty attributed strings were equal, so I put in a non-empty string. I'll check the actual hash values to ensure they have a good spread.

2023-08-21 21:45 UTC, cobbal commented on Sources/FishyJoesCSharpRuntime/AttributedString/AttributedString.Runs+cSharp.swift
> +            .map { AttributedString("HASH", attributes: $0.attributes).hashValue }
For the run we should have the actual string contents as well as the attributes, shouldn't we? Or am I misunderstanding runs?

2023-08-23 22:01 UTC, cobbal approved these changes

2023-08-23 22:34 UTC, merged