Wasm Support for Runtime
cricut/FishyJoes pull request #127
Opened 2023-08-24 16:30 UTC by mstokercricut

* Made changes necessary to reference the node runtime from Wasm
* Documented CodeGen.swift

2023-08-25 17:45 UTC, cobbal requested changes

2023-08-25 17:45 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +            // Locate sources to translate
In particular, this is locating dependency sources. e.g. CriGeo (not -bindings) and FishyJoes

2023-08-25 17:45 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +            // Prepare destination directories for the Swift-side interface files for the translated foreign languages
This is cleaning/creating any directories that will be referenced by the sourcery-side generator, not just swift

2023-08-25 17:45 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +            let configuration = BuildConfiguration(
I'm a little surprised this move was possible. I didn't realize build was the only step to rely on the configuration.

2023-08-25 17:45 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +                try cmd("mkdir", "-p", outputDir).run()
It's a bug to merge these 2 loops, since outputDir may be the same between 2 platforms.

2023-08-25 17:45 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +                    // Configure wasm-opt to optimize Wasm bundles
What this block really does is installs the wasm blob into the output. It either uses `wasm-opt` or `cp` depending on settings and installed software.

2023-08-25 17:45 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +                    let runtimeDirectorySearchLocations = [".build/checkouts/FishyJoes/node-runtime", "../../node-runtime"]
This feels very fragile and is missing at least 1 case. Also, I don't like seeing any testapi-specific config outside of the `integration-tests` directory.

2023-08-25 17:45 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +                    let runtimeDirectorySearchLocations = [".build/checkouts/FishyJoes/node-runtime", "../../node-runtime"]
Probably grab the result of `packageInfo.dependencyMap["fishyjoes"]` from the much earlier guard statement like we do for other dependencies

2023-08-25 17:45 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +                    // Create the required Javascript files for loading the module's Wasm bundle from a web browser
This is both for browser and non-browser

2023-08-25 17:45 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +                    // Configure loading of Javascript extensions when the Wasm bundle is loaded, if provided by dependency modules
This doesn't configure the extensions, it just installs them

2023-08-25 17:45 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +                    // TODO: Compile using Android Studio
This comment is wrong. We compile with gradle exactly as above. Avoiding duplicate compilation is why this was an "if contains". Since kotlinSystem is always present when kotlinAndroids are, the check was simplified to just check for kotlinSystem

2023-08-25 17:45 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +                // Gather environment information to pass on for code-coverage purposes
"environment variables" is more precise and technical than "information"

2023-08-25 17:45 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +                    // TODO: Pack using maven
nothing to do here

2023-08-25 17:45 UTC, cobbal commented on Sources/FishyJoesExecutionHelper/main.swift
> +enum DeprecatedNSKeyedUnarchiver: UndeprecatedNSKeyedUnarchiver {
Nice workaround. The enum is unneccesary though, you can directly do
```
extension NSKeyedUnarchiver: UndeprecatedNSKeyedUnarchiver {}
```

2023-08-28 16:00 UTC, mstokercricut commented on Sources/FishyJoesExecute/CodeGen.swift
> +            let configuration = BuildConfiguration(
Given its name `BuildConfiguration` I was pleased to see it. 😁

2023-08-28 21:17 UTC, mstokercricut commented on Sources/FishyJoesExecutionHelper/main.swift
> +enum DeprecatedNSKeyedUnarchiver: UndeprecatedNSKeyedUnarchiver {
Not sure what's going on, but using an extension causes Sourcery to puke: 

Generating code...
error: .build/debug/FishyJoes_FishyJoesExecutionHelper.bundle/FishyJoes.swifttemplate: Swift/ErrorType.swift:200: Fatal error: Error raised at top level: SwiftTemplate.ProcessError(description: "xcrun [\"--executing-from-within-sourcery\", \"/var/folders/wc/svg0n55n0rv5fj3y71npvjjm0000gp/T/SwiftTemplate/1.9.2/context.bin\"] exited with code 4")

2023-08-28 21:24 UTC, cobbal commented on Sources/FishyJoesExecutionHelper/main.swift
> +enum DeprecatedNSKeyedUnarchiver: UndeprecatedNSKeyedUnarchiver {
Works on my machine :shrug:

2023-08-28 21:30 UTC, cobbal approved these changes

2023-08-29 14:33 UTC, merged