Coverage
cricut/FishyJoes pull request #144
Opened 2023-11-10 00:28 UTC by mstokercricut

2023-11-28 21:49 UTC, cobbal requested changes

2023-11-28 21:49 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedFunction.swift
> +        self.nodeName = "(\(parameters.enumerated().map { "_\($0.offset): \($0.element.definingTSNamespace.map { "\($0)." } ?? "")\($0.element.nodeName)" }.joined(separator: ", "))) => \(returnType.d
Use `.nodeType` instead to get the namespaced version.

2023-11-28 21:49 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +            // Prepare to execute the fishy-joes-execution-helper via Sourcery by assembling an environment
This is a worse description of the overarching task; it just describes the first step.

2023-11-28 21:49 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +                    if platform == .wasm {
I don't like "if a { ... }; if b { ... }; if a { ... }; if b { ... }" thing here. I would prefer to group the platforms together

2023-11-28 21:49 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +                                    ln -sf "$(realpath $package_directory/\(dependency.npmPackageName)/\(dependency.nodeLibName))" "\(dependency.compiledLibName)"
quote variables in bash

2023-11-28 21:49 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +                        let prettyEncoder = JSONEncoder()
I created a PrettyJsonEncoder in utilities.swift. Use it instead

2023-11-28 21:49 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +                        try cmd("echo")
PrettyJSONEncoder makes this unneeded

2023-11-28 21:49 UTC, cobbal commented on Sources/FishyJoesIotaRuntime/AttributedString/AttributedSubstring+iota.swift
> +        let equal = lhsString.characters.isEmpty && rhsString.characters.isEmpty ? true : lhsString == rhsString
The technical term for "? true :" is "or"

2023-11-28 21:49 UTC, cobbal commented on integration-tests/TestAPI-bindings/node-test/AttributedStrings.test.ts
> +    // expect(substring.substring.equals(substring))
Are these meant to be commented out?

2023-11-29 18:20 UTC, mstokercricut commented on Sources/FishyJoesIotaRuntime/AttributedString/AttributedSubstring+iota.swift
> +        let equal = lhsString.characters.isEmpty && rhsString.characters.isEmpty ? true : lhsString == rhsString
The technical term for the whole expression is `==`, but I suppose one less ternary in the world is a net win.

2023-11-29 18:25 UTC, mstokercricut commented on integration-tests/TestAPI-bindings/node-test/AttributedStrings.test.ts
> +    // expect(substring.substring.equals(substring))
🤦

2023-11-29 20:05 UTC, cobbal approved these changes

2023-11-30 22:23 UTC, merged