Node.js Windows Support
cricut/FishyJoes pull request #148
Opened 2023-12-08 20:16 UTC by mstokercricut

* Adds Windows 10 as a supported target platform via Node.js and TypeScript
* Changes how Wasm module registration is done to fit better with how it must be done for Node.js
* Provides several improvements to the Platform type for use in code generation

2024-01-17 17:08 UTC, cobbal commented on Sources/FishyJoesExecute/Resources/bindings-template/Package.swift
> +            url: "https://github.com/cricut/FishyJoes", .branch(fishyJoesVersion)
This is a very annoying change, as any time the template is run "swift run fishy-joes" will never work. Before it would sometimes work (especially in development)

2024-03-11 18:37 UTC, cobbal requested changes

2024-03-11 18:37 UTC, cobbal commented on .github/workflows/integration-tests.yaml
> +          # TODO: Wasm build support on Windows (needs SwiftWasm compiler)
Not really a TODO. We don't test wasm on mac either. We don't need to test it on every platform, as that's testing that's a part of swift-wasm, not part of this repo.

2024-03-11 18:37 UTC, cobbal commented on .github/workflows/integration-tests.yaml
> +          $SWIFT run -- fishy-joes --nodejs build test
might be best practice to quote `"$SWIFT"`. Windows is known for putting spaces in program paths, even if the swift package doesn't

2024-03-11 18:37 UTC, cobbal commented on .github/workflows/integration-tests.yaml
> +          #$SWIFT run -- fishy-joes --dart build test
https://github.com/cricut/CriGeo-bindings/blob/main/.github/workflows/dart.yaml#L161-L162 (powershell)

No need to put it in the current directory, just make sure the Path includes it

2024-03-11 18:37 UTC, cobbal commented on .github/workflows/iota-runtime.yaml
> +          mkdir -p $LIB_DIR
quote LIB_DIR here if it's quoted in the next line for consistency.

2024-03-11 18:37 UTC, cobbal commented on Package.swift
>          T.target(name: "FishyJoesCommonRuntime"),
This one is not java-specific

2024-03-11 18:37 UTC, cobbal commented on Package.swift
> +                    .unsafeFlags(["-Xlinker", "/LIBPATH:.\\.build\\checkouts\\FishyJoes\\Sources\\NodeAPIResolve\\lib\\windows.x86_64"], .when(platforms: [.windows])),
This feels incredibly fraglie

2024-03-11 18:37 UTC, cobbal commented on Sources/FishyJoesCore/Translators/CSharpTranslator.swift
> +        return value == "nil" ? "null" : literal(value: value)
I really don't like this being centralized. Essentially it's asserting that any valid swift code is valid C# and JS and kotlin.

2024-03-11 18:37 UTC, cobbal commented on Sources/FishyJoesCore/Translators/NodeTranslator.swift
> +        nodeTypeListFragment.outputBlock("public func registerModule\(context.module.name)C(env: napi_env, exports: napi_value) -> napi_value? {") {
nit: It's really hard to see the name difference. Putting it at the front would be more obvious: "cRegisterModuleCriGeo"

2024-03-11 18:37 UTC, cobbal commented on Sources/FishyJoesCore/Translators/NodeTranslator.swift
> +        nodeTypeListFragment.outputBlock("public func registerModule\(context.module.name)C(env: napi_env, exports: napi_value) -> napi_value? {") {
Or should this one be "registerModuleCriGeo" and the other one just "CriGeo_NodeInterface.registerModule" since it doesn't need a cdecl symbol?

None of this really matters much I suppose

2024-03-11 18:37 UTC, cobbal commented on Sources/FishyJoesCore/Translators/NodeTranslator.swift
> +        nodeNativeShimFragment.output("#include <node_api.h>")
Could benefit from outputting some blank lines in here. The generated file looks dense and hard to read

2024-03-11 18:37 UTC, cobbal commented on Sources/NodeAPIResolve/win_delay_load_hook.cc
> +#define HOST_BINARY "node.exe"
Is this the name of the binary in design space? Could be an issue.

2024-03-11 18:37 UTC, cobbal commented on documentation/FishyJoes Hello World.txt
This is very rough documentation. A couple ideas for improvement:

 - use markdown
 - put some context in, instead of a raw terminal dump
 - please no spaces in file names
 - even I have no idea what you're referring to under "Temporary Fixes"

2024-03-11 18:37 UTC, cobbal commented on integration-tests/TestAPI-bindings/node-test/AttributedStrings.test.ts
> +})
Is this supposed to be committed?

2024-03-11 18:37 UTC, cobbal commented on integration-tests/TestAPI-bindings/node-test/package.json
> +    "test-native-windows-lldb": "lldb -- node --force-node-api-uncaught-exceptions-policy --experimental-vm-modules node_modules/jest/bin/jest.js --run-in-band --detect-open-handles --force-exit --de
Good additions, but this file is becoming very terrible. I wonder if there's a way to abstract the common options.

2024-03-11 18:37 UTC, cobbal commented on integration-tests/TestAPI-bindings/node-test/package.json
> +    "@cricut/testapi-native-windows": "file:../output/node-native-windows",
Why is windows special? Or was this a stray "npm install" that caused this?

2024-03-11 18:37 UTC, cobbal commented on node-runtime/fishyjoes-runtime-native-macos/Runtime.js
> +const { Optional, Runtime } = require('./Runtime.cjs');
Does optional exist in javascript? I thought it was just a type.

2024-03-11 18:37 UTC, cobbal commented on node-runtime/fishyjoes-runtime-native-ubuntu/package.json
> -    "postinstall": "./postinstall.sh"
yay!

2024-03-11 18:37 UTC, cobbal commented on scripts/compile-node-runtime.sh
> +SHIM_DIR="Sources/FishyJoesNodeRuntime_NodeNativeShim"
This is not a source of FishyJoes/package.swift, it probably doesn't belong in Sources. Probably should go in node-runtime instead?

2024-03-11 23:30 UTC, mstokercricut commented on Sources/FishyJoesCore/Translators/CSharpTranslator.swift
> +        return value == "nil" ? "null" : literal(value: value)
It does? It looks like it translates "nil" to "null", then tries to translate the value as a literal, which all our languages share a common definition for. If that fails, it reports that the value could not be translated.

Am I missing something? Potentially Swift's string conversion of a double value may not work in C# as a literal in its compiler, but I think that they all do...

2024-03-11 23:36 UTC, mstokercricut commented on Sources/NodeAPIResolve/win_delay_load_hook.cc
> +#define HOST_BINARY "node.exe"
Ya, it could be. If it isn't "node.exe" somewhere in the path, though, how would we ever be able to find it reliably?

2024-03-11 23:37 UTC, mstokercricut commented on integration-tests/TestAPI-bindings/node-test/AttributedStrings.test.ts
> +})
Nope.

2024-03-11 23:40 UTC, mstokercricut commented on integration-tests/TestAPI-bindings/node-test/package.json
> +    "test-native-windows-lldb": "lldb -- node --force-node-api-uncaught-exceptions-policy --experimental-vm-modules node_modules/jest/bin/jest.js --run-in-band --detect-open-handles --force-exit --de
If npm can call back into npm, we could do that. E.g.

"test-native-windows-lldb": "lldb -- npm run test-native-windows"

I figured that npm might actually then call out to node, so lldb would then miss the part we actually want debugged. In fact, on Windows, it almost certainly does this. Without generating package.json, adding this without duplication seems impossible to me. Maybe adding some environment variables or something, but that seems worse...

2024-03-11 23:44 UTC, mstokercricut commented on node-runtime/fishyjoes-runtime-native-macos/Runtime.js
> +const { Optional, Runtime } = require('./Runtime.cjs');
Not that I can find. You actually added the original definition for `Optional`.

2024-03-11 23:46 UTC, mstokercricut commented on node-runtime/fishyjoes-runtime-native-ubuntu/package.json
> -    "postinstall": "./postinstall.sh"
I wish this could actually go away. The definition just moved to CodeGen.swift line 600. For safety, I had macOS do the symlink too.

2024-03-12 00:12 UTC, mstokercricut commented on documentation/FishyJoes Hello World.txt
I'll toy with it a bit more before including it

2024-03-12 00:15 UTC, mstokercricut commented on Package.swift
> +                    .unsafeFlags(["-Xlinker", "/LIBPATH:.\\.build\\checkouts\\FishyJoes\\Sources\\NodeAPIResolve\\lib\\windows.x86_64"], .when(platforms: [.windows])),
I agree. There must be a better way. Require that on Windows a dev adds Node to the system lib path?

By moving to using clang to compile the shim, 1 of these went away at least.

2024-03-15 00:29 UTC, mstokercricut commented on node-runtime/fishyjoes-runtime-native-macos/Runtime.js
> +const { Optional, Runtime } = require('./Runtime.cjs');
Removed! Annoying to track the js and ts exports separately, but done.

2024-03-15 18:30 UTC, cobbal approved these changes
This is looking very solid.

2024-03-15 18:30 UTC, cobbal commented on Package.swift
> +let extraLibPath = env["EXTRA_LIBPATH"]?.split(separator:";") ?? []
lint: space after ":"

2024-03-15 18:30 UTC, cobbal commented on Package.swift
> +let extraLibPath = env["EXTRA_LIBPATH"]?.split(separator:";") ?? []
Would you mind also adding Package.swift to the "included" section of swiftlint.yaml?

2024-03-15 18:30 UTC, cobbal commented on Package.swift
> +                    Array(extraLibPath.map { ["-Xlinker", "/LIBPATH:\($0)"] }.joined()),
Just use flatMap here

2024-03-15 18:30 UTC, cobbal commented on Package.swift
> +                // On Windows, node.lib must be in the LIB environment variable when building FishyJoes, the runtime, or bindings libraries, via "swift build"
We're not actually using LIB env var, are we? This is all being passed by flags and differently named vars

2024-03-15 18:30 UTC, cobbal commented on Sources/FishyJoesExecute/DownloadNodeLib.swift
> +        force: Bool? = nil
nit: force doesn't need to be optional

2024-03-15 22:20 UTC, mstokercricut commented on Package.swift
> +let extraLibPath = env["EXTRA_LIBPATH"]?.split(separator:";") ?? []
👍🏿

2024-03-19 00:50 UTC, merged