Bscothern/async -> main
cricut/FishyJoes pull request #161
Opened 2024-01-12 20:59 UTC by cobbal

2024-01-12 21:24 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +            return .function(signature: functionType.kotlinName, parmeters: functionType.parameters.map(\.kotlinType))
What happens to the async bool here?

2024-01-12 21:29 UTC, cobbal commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +                (name: "_successContinuation", type: "Function1Converter<\(returnType)\(returnType.hasSuffix("Converter") ? "" : ".CType"), VoidConverter>.CType"),
This is always the converter type, returnType should probably be returnConverterType, and should always have .CType (as that's part of the protocol)

2024-01-12 21:35 UTC, cobbal commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +                            fragment.output("\(method.isMutating ? "var" : "let") value: Result<\(method.returnType.name), any Error>\(method.isMutating ? "!" : "")")
I think this can just be let?

2024-01-12 21:42 UTC, cobbal commented on Sources/FishyJoesJavaRuntime/Env.swift
> +            guard attachStatus == JNI_OK else {
Should the thread-local count be 0 if an error happens here?

2024-01-12 21:44 UTC, cobbal commented on Sources/FishyJoesJavaRuntime/Env.swift
> +            let jvmAttachCount = Thread.current.threadDictionary.value(forKey: Env.jvmAttachCountKey) as? Int ?? 1
Could use a comment like "The JVM is attached to this thread by something other than FishyJoes, start the ref count at 1 so that we don't detach a thread we don't own"

2024-01-12 21:45 UTC, cobbal commented on Sources/FishyJoesJavaRuntime/Env.swift
> +        Thread.current.threadDictionary.setValue(jvmAttachCount - 1, forKey: Env.jvmAttachCountKey)
This should probably be deferred

2024-01-12 23:53 UTC, mstokercricut requested changes
Several things need addressing before merge.

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +                        let kotlinType: String = (method.isSuspend && parameter.type.isFunction) ? "(suspend \(parameter.type.kotlinType.dropFirst())" : parameter.type.kotlinType
A comment like "Rather than allowing a suspend function to take in another non-suspend function, we have decided to explicitly disallow that configuration so this does not need to be recursive"

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +                                                            // TODO: Forward parameters
Nuke this?

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +                                            if parameter.type.isFunction {
Why are we looking at function parameters directly? This should compose nicely if dispatched to the type (AsyncFunctionConverter) to handle...

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +                            (labelComment: nil, name: "successContinuation", type: .named(package: nil, name: "(\(method.returnType.kotlinType)\(method.returnType.kotlinType == "kotlin.Unit" ? "?" :
Put tuple arguments on their own lines?

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +        kotlinType.contains("->")
Change to switch on self, and return true in `function` case.

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +        fragment.output("@OptIn(ExperimentalCoroutinesApi::class)")
Should only output this for async? Or just on everything?

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesJavaRuntime/JavaFunction.swift
> +        return try env.NewObject(SwiftAsyncFunctionImpl.implClass, SwiftAsyncFunctionImpl.constructor, jvalue(i: 0), ptr)
Arity of 1?

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesJavaRuntime/JavaFunction.swift
> +        return try env.NewObject(SwiftAsyncFunctionImpl.implClass, SwiftAsyncFunctionImpl.constructor, jvalue(i: 0), ptr)
Arity of 2?

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesJavaRuntime/JavaFunction.swift
> +        return try env.NewObject(SwiftAsyncFunctionImpl.implClass, SwiftAsyncFunctionImpl.constructor, jvalue(i: 0), ptr)
Arity of 3?

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesJavaRuntime/JavaFunction.swift
> +        return try env.NewObject(SwiftAsyncFunctionImpl.implClass, SwiftAsyncFunctionImpl.constructor, jvalue(i: 0), ptr)
Arity of 4?

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesJavaRuntime/JavaFunction.swift
> +        return try env.NewObject(SwiftAsyncFunctionImpl.implClass, SwiftAsyncFunctionImpl.constructor, jvalue(i: 0), ptr)
Arity of 5?

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesJavaRuntime/JavaFunction.swift
> +        return try env.NewObject(SwiftAsyncFunctionImpl.implClass, SwiftAsyncFunctionImpl.constructor, jvalue(i: 0), ptr)
Arity of 6?

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesJavaRuntime/JavaReference.swift
> +    public convenience init<T: JavaConverter>(local: T, env: Env) throws where T.SwiftType == T, T.CType == T {
Is this something we need?

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesJavaRuntime/JavaReference.swift
> +                try? Env.relenquishJVMThread(on: vm)
Should be `try!`?

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesJavaRuntime/Utils.swift
> +            print(origin.joined(separator: "\n"))
Comment this?

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesJavaRuntime/Utils.swift
> +    let origin = Thread.callStackSymbols
Comment this?

2024-01-12 23:53 UTC, mstokercricut commented on Sources/FishyJoesJavaRuntime/Utils.swift
> +    // TODO: See if there is a way to do this with Kotlin concurrency that exposes better ways to wait for values than swift...
This may need doing before merge

2024-01-12 23:53 UTC, mstokercricut commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/AttributedStringTests.kt
> +/*
Uhh... this needs to work.

2024-01-12 23:53 UTC, mstokercricut commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/StructTests.kt
> +//    @Test
This test should probably be working before we merge...

2024-01-12 23:53 UTC, mstokercricut commented on integration-tests/TestAPI/Sources/TestAPI/Functions.swift
> +    public static func async42Func() async throws -> Int {
These should be variables of function types, not methods defined on `Functions`...

2024-01-12 23:53 UTC, mstokercricut commented on integration-tests/TestAPI/Sources/TestAPI/Structs.swift
> +//        /// <!-- FishyJoes.export(increment) -->
These should be working before merge...

2024-01-16 14:03 UTC, rodzikkonrad commented on Sources/FishyJoesJavaRuntime/Env.swift
> +    ///     The returned `Env` should generally be assigned to the inout `javaEnv` in order to avoid shadowing and let the current environment propigate back out.
"propigate" typo

2024-01-16 14:08 UTC, rodzikkonrad commented on Sources/FishyJoesJavaRuntime/Env.swift
> +            let jvmAttachCount = Thread.current.threadDictionary.value(forKey: Env.jvmAttachCountKey) as? Int ?? 1
is it ok that is set to 1 in above line (when there is nothing in the dictionary under that key) and then its increased by one on the line below?

2024-01-16 14:11 UTC, rodzikkonrad commented on Sources/FishyJoesJavaRuntime/Env.swift
> +            guard attachStatus == JNI_OK else {
yeah, it seems that: 
Thread.current.threadDictionary.setValue(1, forKey: Env.jvmAttachCountKey)
Should be after "guard"

2024-01-16 14:15 UTC, rodzikkonrad commented on Sources/FishyJoesJavaRuntime/Env.swift
> +//        print(Thread.callStackSymbols.joined(separator: "\n"))
remove unused code

2024-01-16 17:21 UTC, bscothern-Cricut commented on Sources/FishyJoesJavaRuntime/Env.swift
> +            guard attachStatus == JNI_OK else {
Fixed.

2024-01-16 17:23 UTC, bscothern-Cricut commented on Sources/FishyJoesJavaRuntime/Env.swift
> +        Thread.current.threadDictionary.setValue(jvmAttachCount - 1, forKey: Env.jvmAttachCountKey)
Fixed.

2024-01-16 17:28 UTC, bscothern-Cricut commented on Sources/FishyJoesJavaRuntime/Env.swift
> +            let jvmAttachCount = Thread.current.threadDictionary.value(forKey: Env.jvmAttachCountKey) as? Int ?? 1
Yes, it defaults to 1 because something else owns the thread and we don't want to detach it. If that thread is ever detached and then calls back into swift somehow when swift attempts to acquire the thread it will detect that it is detached and set the count back to 1 so it can detach again when needed. I've added a comment helping explain the logic.

2024-01-16 17:32 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +                            fragment.output("\(method.isMutating ? "var" : "let") value: Result<\(method.returnType.name), any Error>\(method.isMutating ? "!" : "")")
Yes it can now. Fixed.

2024-01-16 17:43 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +                                                            // TODO: Forward parameters
Fixed.

2024-01-16 17:44 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +                            (labelComment: nil, name: "successContinuation", type: .named(package: nil, name: "(\(method.returnType.kotlinType)\(method.returnType.kotlinType == "kotlin.Unit" ? "?" :
Fixed.

2024-01-16 17:45 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +        kotlinType.contains("->")
Ya I added the function case and never got back to updating this. Fixed.

2024-01-16 17:47 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +        fragment.output("@OptIn(ExperimentalCoroutinesApi::class)")
It is only needed for async but doesn't hurt anything being there unless we end up building something where we don't want async symbols at all.

2024-01-16 17:49 UTC, bscothern-Cricut commented on Sources/FishyJoesJavaRuntime/JavaFunction.swift
> +        return try env.NewObject(SwiftAsyncFunctionImpl.implClass, SwiftAsyncFunctionImpl.constructor, jvalue(i: 0), ptr)
Fixed copy pasta error.

2024-01-16 17:49 UTC, bscothern-Cricut commented on Sources/FishyJoesJavaRuntime/JavaFunction.swift
> +        return try env.NewObject(SwiftAsyncFunctionImpl.implClass, SwiftAsyncFunctionImpl.constructor, jvalue(i: 0), ptr)
Fixed copy pasta error.

2024-01-16 17:49 UTC, bscothern-Cricut commented on Sources/FishyJoesJavaRuntime/JavaFunction.swift
> +        return try env.NewObject(SwiftAsyncFunctionImpl.implClass, SwiftAsyncFunctionImpl.constructor, jvalue(i: 0), ptr)
Fixed copy pasta error.

2024-01-16 17:49 UTC, bscothern-Cricut commented on Sources/FishyJoesJavaRuntime/JavaFunction.swift
> +        return try env.NewObject(SwiftAsyncFunctionImpl.implClass, SwiftAsyncFunctionImpl.constructor, jvalue(i: 0), ptr)
Fixed copy pasta error.

2024-01-16 17:49 UTC, bscothern-Cricut commented on Sources/FishyJoesJavaRuntime/JavaFunction.swift
> +        return try env.NewObject(SwiftAsyncFunctionImpl.implClass, SwiftAsyncFunctionImpl.constructor, jvalue(i: 0), ptr)
Fixed copy pasta error.

2024-01-16 17:49 UTC, bscothern-Cricut commented on Sources/FishyJoesJavaRuntime/JavaFunction.swift
> +        return try env.NewObject(SwiftAsyncFunctionImpl.implClass, SwiftAsyncFunctionImpl.constructor, jvalue(i: 0), ptr)
Fixed copy pasta error.

2024-01-16 17:50 UTC, bscothern-Cricut commented on Sources/FishyJoesJavaRuntime/JavaReference.swift
> +    public convenience init<T: JavaConverter>(local: T, env: Env) throws where T.SwiftType == T, T.CType == T {
Yes, otherwise special casing and logic is needed to handle primitives when being boxed to pass into/out of async land because of `@Sendable`

2024-01-16 17:51 UTC, bscothern-Cricut commented on Sources/FishyJoesJavaRuntime/JavaReference.swift
> +                try? Env.relenquishJVMThread(on: vm)
Yes, that is what we decided on after I got it added in over here.

2024-01-16 17:52 UTC, bscothern-Cricut commented on Sources/FishyJoesJavaRuntime/Utils.swift
> +            print(origin.joined(separator: "\n"))
Eh it was debugging stuff. I removed it.

2024-01-16 17:52 UTC, bscothern-Cricut commented on Sources/FishyJoesJavaRuntime/Utils.swift
> +    let origin = Thread.callStackSymbols
It was for debugging and has been removed.

2024-01-16 17:53 UTC, bscothern-Cricut commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/AttributedStringTests.kt
> +/*
Ya I forgot I turned these off...

2024-01-16 18:03 UTC, bscothern-Cricut commented on Sources/FishyJoesJavaRuntime/Env.swift
> +//        print(Thread.callStackSymbols.joined(separator: "\n"))
Fixed.

2024-01-16 18:05 UTC, bscothern-Cricut commented on Sources/FishyJoesJavaRuntime/Env.swift
> +    ///     The returned `Env` should generally be assigned to the inout `javaEnv` in order to avoid shadowing and let the current environment propigate back out.
Fixed.

2024-01-16 20:04 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +                            fragment.output("\(method.isMutating ? "var" : "let") value: Result<\(method.returnType.name), any Error>\(method.isMutating ? "!" : "")")
So I am reverting this back to var or let because it needs to be the force unwrapped var version for mutating functions because the reference has to escape. This might change with some of the other changes that end up happening though.

2024-01-17 13:19 UTC, rodzikkonrad commented on Sources/FishyJoesJavaRuntime/Env.swift.orig
> +>>>>>>> c39aecc (Addressed a bunch of PR comments, fixed typos, logic bugs, etc)
file committed with conflicts

2024-01-17 20:59 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +                (name: "_successContinuation", type: "Function1Converter<\(returnType)\(returnType.hasSuffix("Converter") ? "" : ".CType"), VoidConverter>.CType"),
Fixed.

2024-01-17 21:00 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +            return .function(signature: functionType.kotlinName, parmeters: functionType.parameters.map(\.kotlinType))
This type is mostly needed to ensure that parameters that are functions can properly be marked as suspend funcs. I added a isSuspend value to the enum case as well so if/when it is needed it is already there since it is an important part of the function.

2024-01-17 21:04 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +                                            if parameter.type.isFunction {
Because I am generating a bunch of Kotlin code that does dynamic and magical changing of context and the `this` object as you call the functions. The suspend func isn't just a pointer to the JNI function like our other function types. It has a body that does all the handling of that context switching and then calls out to the JNI. It is likely doable in the JNI layer but would be way way more complex to generate and manage over there.

2024-01-17 21:04 UTC, bscothern-Cricut commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/StructTests.kt
> +//    @Test
Fixed.

2024-01-17 21:05 UTC, bscothern-Cricut commented on integration-tests/TestAPI/Sources/TestAPI/Structs.swift
> +//        /// <!-- FishyJoes.export(increment) -->
Fixed.

2024-01-17 21:06 UTC, bscothern-Cricut commented on Sources/FishyJoesJavaRuntime/Env.swift.orig
> +>>>>>>> c39aecc (Addressed a bunch of PR comments, fixed typos, logic bugs, etc)
Fixed.

2024-01-17 23:12 UTC, bscothern-Cricut commented on integration-tests/TestAPI/Sources/TestAPI/Functions.swift
> +    public static func async42Func() async throws -> Int {
Fixed.

2024-01-30 20:29 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +                        let kotlinType: String = (method.isSuspend && parameter.type.isFunction) ? "(suspend \(parameter.type.kotlinType.dropFirst())" : parameter.type.kotlinType
Suspend callbacks and synchronous methods can now be freely mixed

2024-01-30 20:29 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +                                            if parameter.type.isFunction {
Now fixed

2024-01-31 17:51 UTC, mstokercricut approved these changes

2024-01-31 17:51 UTC, mstokercricut commented on Sources/FishyJoesCommonRuntime/Future.swift
> +public final class Future<Output> {
This is totally internal to FishyJoes, but I wonder if we should be adding docs to the major structure of the library as a whole. There is a lot of complexity, so documenting individual types that are used may help a future reader. The link is ultimately the best piece of documentation, but documenting in-code could help.

2024-01-31 17:51 UTC, mstokercricut commented on Sources/FishyJoesCommonRuntime/Future.swift
> +// Based on https://cs3110.github.io/textbook/chapters/ds/promises.html#the-full-implementation
This is helpful documentation.

2024-01-31 17:51 UTC, mstokercricut commented on Sources/FishyJoesCommonRuntime/Future.swift
> +                    fatalError("Future resolved twice, first \(state), then \(result)")
Great check. Any fear that this actually occurs?

2024-01-31 17:51 UTC, mstokercricut commented on Sources/FishyJoesCommonRuntime/Future.swift
> +        self.init()
That *is* unfortunate. Can it be `let (s, promise) = Future.make(); self = s`? Or does the compiler look for an explicit, direct call to another initializer?

2024-01-31 17:51 UTC, mstokercricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedFunction.swift
> +        self.jniType = .object("kotlin/jvm/functions/Function\(parameters.count + (isAsync ? 1 : 0))")
A bit magic. Would it be less confusing to actually add a parameter to `parameters`, or would the added complexity of doing that make it more confusing?

2024-01-31 17:51 UTC, mstokercricut commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> -                } else if method.isSuspend {
Sooooo nice.

2024-01-31 17:51 UTC, mstokercricut commented on Sources/FishyJoesJavaRuntime/Env.swift
> +            // So by defaulting to a count of 1 we prevent detaching via FishyJoes and let the owner detach when it decides it is appropriate.
This would be difficult to follow without the comment. Great addition.

2024-01-31 17:51 UTC, mstokercricut commented on Sources/FishyJoesJavaRuntime/Utils.swift
> +/// Calls the given body while ensuring that the body closure is attached to the JVM.
Good docs. I assume there is no way for us to check when this hasn't been done, right? The docs are the only way to ensure this relationship is maintained?

2024-01-31 17:56 UTC, cobbal commented on Sources/FishyJoesCommonRuntime/Future.swift
> +                    fatalError("Future resolved twice, first \(state), then \(result)")
It's a public function, and therefore permitted by the API. Java futures have documented behavior when resolved twice, so it's very possible that that behavior will happen somewhere.

2024-01-31 17:56 UTC, cobbal commented on Sources/FishyJoesCommonRuntime/Future.swift
> +                    fatalError("Future resolved twice, first \(state), then \(result)")
Maybe we should pick a non-crashy behavior when it happens (just take the first result), but I'd like to know it's happening before doing that.

2024-01-31 17:57 UTC, cobbal commented on Sources/FishyJoesCommonRuntime/Future.swift
> +        self.init()
With classes it doesn't work

2024-01-31 17:58 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedFunction.swift
> +        self.jniType = .object("kotlin/jvm/functions/Function\(parameters.count + (isAsync ? 1 : 0))")
We aren't able to deal with the type on the swift side (a kotlin continuation), so it's entirely handled on the kotlin side. It does show up in the JNI interface though, which is why it's here

2024-01-31 18:00 UTC, cobbal commented on Sources/FishyJoesJavaRuntime/Utils.swift
> +/// Calls the given body while ensuring that the body closure is attached to the JVM.
I think this one is in the "stare carefully at the code" bucket. Fortunately, not many places call this method

2024-02-01 21:03 UTC, merged