AB#424516 Use Dart sealed class for enums and eliminate used of freezer for Dart Enums
cricut/FishyJoes pull request #163
Opened 2024-01-20 00:16 UTC by dvosscricut

Dart does allow for the use of named parameters in constructors, which would allow us to respect Swift named parameter names, but since the current code doesn't support that, to be backwards compatible I continued the tradition of using unnamed positional parameters in Dart, regardless of whether the Swift parameter was named or unnamed.

Freezed is still used by non enum types, namely structs defined in extensions forPuttingTypesIntoQuestionablePlaces, as well as for a struct inside the Collections enum, among others, but I thought I'd get things rolling so we can sort out particulars for this PR first before I went on that deep dive.

2024-01-20 01:37 UTC, mstokercricut requested changes
This is an excellent start! If you'd like to merge into main after addressing these comments, that would be fine. However, there is little need to do a versioned release before completely eliminating Freezed.

2024-01-20 01:37 UTC, mstokercricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                    fragment.output("throw UnsupportedError('This class is supposed to be unihabited');")
`uninhabited`

2024-01-20 01:37 UTC, mstokercricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                    fragment.output("throw UnsupportedError('Unknown \(unqualifiedName) subclass');")
The previous implementation did not throw from what I could tell. Maybe the `map` could somehow. Can you see any way we can eliminate the need to throw?

2024-01-20 01:37 UTC, mstokercricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                        if enumIndex != 0 {
Since these all return, there is no need for `else if`. If you do want to keep the `else if` structure, though, the final statement should be an `else`.

2024-01-20 01:37 UTC, mstokercricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                fragment.output("bool operator ==(Object other)", newLineTerminated: false)
I didn't see any tests for `==` or `hashCode`. Since we're now taking charge of those operations, we should test them in `TestAPI-bindings` for Dart.

E.g. test if self equality works, if two instances of the same case work, test a few associated data enums for equality, and test if equal instances have the same hash value.

A test placing all of the cases of an enum into a Set would probably also be called for, ensuring that they can be used correctly as option flag collections.

2024-01-20 01:37 UTC, mstokercricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
>      override var hasFreezedPart: Bool {
References to Freezed should eventually be completely eliminated.

2024-01-20 04:03 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                    fragment.output("throw UnsupportedError('Unknown \(unqualifiedName) subclass');")
we could have an else that returned 0 (the first enum case).

However I believe throwing and exception is quite appropriate if we ever get an object that is not one of the known enum cases.

2024-01-20 04:04 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                        if enumIndex != 0 {
yes, I could do an else as the final statement and throw the exception there.

2024-01-20 04:05 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                fragment.output("bool operator ==(Object other)", newLineTerminated: false)
The tests exist in the enumTests. Any expect(..., equals()) uses it. (enum_test.dart).

If you don't have the == and hashCode, then the tests in enum_test.dart won't work

2024-01-21 01:26 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
>      override var hasFreezedPart: Bool {
I agree!

I'm just doing it for enums right now, and structs still use it, so this computed var must still exist.

2024-01-21 01:27 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                    fragment.output("throw UnsupportedError('This class is supposed to be unihabited');")
good catch

2024-01-21 01:28 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                        if enumIndex != 0 {
it's just more complicated to generate that equivalently functioning code. But I will do it, just for you, and for style.

2024-01-21 01:50 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                        if enumIndex != 0 {
actually it wasn't too bad to add it. done!

2024-01-21 01:54 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                    fragment.output("throw UnsupportedError('Unknown \(unqualifiedName) subclass');")
I decided to go with the if/else branching structure instead of the map because it's the same amount of code in the enum discriminator but it cuts down on a lot of bloated boilerplate 'map' code in each the sealed class's subclasses.

It shouldn't be possible to actually reach this else case, but if it is an exception is the proper way to warn/deal with it.

map used overridden subclass functions to pick the appropriate closure passed into it from the many closures passed in (one per subclass). But if a subclass for some reason did not override the map function you would get an exception because it would call the parent map function which does a `throw _privateConstructorUsedError `because it's supposed to be always overridden by a subclass. So it's kind of the same dealy-oh here, just in a different form. If the generator forgot to put in an else case for a subclass, it would throw an unknown subclass type exception in this PR code. On the freezer map type code, it would throw the _privateConstructorUsedError if the generator somehow forgot to override the map function in a subclass.

2024-01-21 01:57 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                fragment.output("bool operator ==(Object other)", newLineTerminated: false)
regardless, I'll make some explicit tests for it.

2024-01-22 17:28 UTC, dvosscricut commented
> This is an excellent start! If you'd like to merge into main after addressing these comments, that would be fine. However, there is little need to do a versioned release before completely eliminating Freezed.

@mstokercricut  
I am blocked from merging without an approval.

2024-01-22 17:29 UTC, mstokercricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                    fragment.output("throw UnsupportedError('Unknown \(unqualifiedName) subclass');")
👍🏿

2024-01-22 17:31 UTC, mstokercricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                fragment.output("bool operator ==(Object other)", newLineTerminated: false)
I was more concerned that the relationship between `equals` and `hashCode` was being respected, and a test for that was made part of the test suite.

2024-01-22 17:32 UTC, mstokercricut approved these changes
This is a pure improvement to existing code, so it can go into main. Hold off on a released version until Freezed is eliminated, though.

2024-01-22 17:54 UTC, merged