AB#424516 Replace freezed gnr8d code for structs with public constructors with our own gnr8d code
cricut/FishyJoes pull request #165
Opened 2024-01-24 03:28 UTC by dvosscricut

AB#424516 Replace freezed gnr8d code for structs with public constructors with our own gnr8d code

I discovered that for the Set, List, and Map there is a built in copy method Set.from(someSet) that I used in shallowCopy.

I also discovered that there is a 20 argument limit for positional parameters input to Object.hash(), so I had to write some code to dive it up into sub Object.hashes input to a top level Object.hash to handle Primitives_PrimitiveHolder. So there is a limit of 20*20=400 positional parameters in structs with public constructors now. That should be enough ("640kiB should be enough for everybody" <:o) ).

I also discovered that DeepCollectionEquality().equals is needed to test if the Set/List/Map types are equal. I found they worked as well for primitive types, so now we just use DeepCollectionEquality().equals in the == operator function instead of what we had before.

2024-01-24 16:32 UTC, mstokercricut requested changes

2024-01-24 16:32 UTC, mstokercricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                                if name == "Set" || name == "List" || name == "Map" {
This seems like a brittle way to identify this case. What if I want a `Cartography.Map`?

2024-01-24 16:32 UTC, mstokercricut commented on integration-tests/TestAPI-bindings/dart/lib/src/generated/Primitives_PrimitiveHolder.dart
> +        Object.hash(
Good catch on this! Glad you found a way to make it work.

2024-01-24 16:32 UTC, mstokercricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> -                        "required \(field.isPubliclyWritable ? "" : "final ")\(field.type.name(in: self)) \(DartClass.deforbidify(field.name))"
Allowing a field that is not publicly writable on the Swift side to be modified causes the interfaces to not match in terms of mutability. Could you expand on why this change is necessary? I saw the test below with `a.x`, but didn't follow the logic...

2024-01-24 16:34 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> -                        "required \(field.isPubliclyWritable ? "" : "final ")\(field.type.name(in: self)) \(DartClass.deforbidify(field.name))"
The 'final' is now in the property declaration list rather than the factory constructor because the factory constructor has been removed in favor of the generative constructor. It's still there though.

2024-01-24 16:36 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                                if name == "Set" || name == "List" || name == "Map" {
As I understand it, the 'name' is really a type (since it's under the DartType type), so Cartography.Map would need to be named Cartography_Map instead because Map/Set/List are built in Dart types. There shouldn't be any naming conflicts

2024-01-24 16:38 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                                if name == "Set" || name == "List" || name == "Map" {
additionally, if somehow there could be a type named "Cartography.Map", the string compare would fail here because it's != "Map" because it compares the entire string.

2024-01-24 16:41 UTC, mstokercricut approved these changes

2024-01-24 18:33 UTC, cobbal requested changes

2024-01-24 18:33 UTC, cobbal commented on Sources/FishyJoesCore/FishyJoesContext.swift
> -                    "import './\(cls.unqualifiedName).dart';", // Import unqualified too or freezed gets confused"
Glad this can be removed

2024-01-24 18:33 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                    fragment.currentIndent += 1
"outputBlock" is the best way to manage indent bookkeeping

2024-01-24 18:33 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                fragment.output("\(unqualifiedName) shallowCopy() => \(unqualifiedName)", newLineTerminated: false)
I can't find the method this is overriding, and I don't see a "shallowCopy" in the old freezed files. Do you have a sample you were basing this on?

2024-01-24 18:39 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                    fragment.currentIndent += 1
good point

2024-01-24 18:41 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                fragment.output("\(unqualifiedName) shallowCopy() => \(unqualifiedName)", newLineTerminated: false)
you're right there is no override for the DartProductClass. Good catch.

2024-01-25 19:00 UTC, mstokercricut approved these changes
LGTM

2024-01-25 19:53 UTC, cobbal approved these changes

2024-01-25 19:59 UTC, merged