AB#427203 Translate Swift Protocols to Dart
cricut/FishyJoes pull request #167
Opened 2024-01-31 23:38 UTC by dvosscricut

AB#427203 Translate Swift Protocols to Dart

Draft because probably should implement other languages C#, Wasm, and Kotlin before a merge so we don't merge strange code.

2024-02-01 00:49 UTC, cobbal requested changes
This looks like a great start. The biggest thing that I see missing is being able to send and receive protocol objects.

2024-02-01 00:49 UTC, cobbal commented on Sources/FishyJoesCore/FishyJoesContext.swift
> +        var translatedTypes = templateContext.types.protocols.compactMap { type -> TranslatedType? in
In #29 this was `types.types` to get both types and protocols

2024-02-01 00:49 UTC, cobbal commented on Sources/FishyJoesCore/ExportAnnotation.swift
> +    let protocols: [String]
We should be able to detect which conformances are exported without manual annotation. See the "matchedConformances" line in #29

2024-02-01 00:49 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        self.storedVariables = type.storedVariables
I didn't think a protocol could have stored variables

2024-02-01 00:49 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +            (type.computedVariables + type.staticVariables).filter { $0.exportAnnotation != nil }
There's an inconsistency here between the methods (which don't require an export annotation) and the variables (which do).

2024-02-01 00:49 UTC, cobbal commented on integration-tests/TestAPI/Sources/TestAPI/Protocols.swift
> +}
There are 2 more things I would expect to see in protocol tests. First is protocols being passed from swift to dart by their type (e.g. `var aProtocolObject: TestMethodsProtocol`) and second is them being passed back (e.g. `func useProtocolObject(aProtocolObject: TestMethodsProtocol)`

2024-02-01 00:49 UTC, cobbal commented on Sources/FishyJoesCore/FishyJoesContext.swift
> +        if dartClass is DartProtocolClass { return }
DartProtocolClass should just have an empty "nativeMethods" then, instead of being dynamically type-sniffed

2024-02-01 00:49 UTC, cobbal commented on Sources/FishyJoesCore/Method.swift
> +            // If param is for protocol method, we need to put in a placeholder name if the swift param is unnamed, because languages like Dart insist on parameter names for their abstract class meth
This seems odd to me. Do you have an example of a dart method signature that is legal in a concrete class, but disallowed in an abstract one?

2024-02-01 00:49 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +            (type.computedVariables + type.staticVariables).filter { $0.exportAnnotation != nil }
I'm not 100% sure which is right.

"just not exporting a method" doesn't really work for a required method of a protocol, since there would be no way for a dart type to then conform to the protocol.

I do like being able to name the exported methods more idiomatically though, so export annotations are good

2024-02-01 00:49 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        return fragment
empty fragments are probably what is causing the swiftlint errors. Just delete this method for now.

2024-02-01 00:49 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        return []
I'm suprised there's no runtime communication between the languages for a protocol. This will probably change once support for passing protocols back and forth is added.

2024-02-01 00:49 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +    struct Typealias {
I don't think Typealias is used

2024-02-01 00:49 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +    let constructor: Constructor
constructor is written, but never read. I don't think it makes sense for this abstract class to have a constructor anyway.

2024-02-01 00:49 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                    fragment.output("// \(method.name) not declared in abstract class because Dart does not support static method inheritance. It will only be put into the subclass that implements th
This could be a problem... should we just forbid exporting protocols with required static methods?

2024-02-01 00:49 UTC, cobbal commented on integration-tests/TestAPI-bindings/dart/lib/src/generated/TestMethodsProtocol.dart
> +abstract class TestMethodsProtocol {
I don't fully understand the difference between "abstract class" and "interface class" in dart, but was suprised to learn you can implement a class you don't inherit from.

2024-02-01 01:09 UTC, dvosscricut commented on Sources/FishyJoesCore/ExportAnnotation.swift
> +    let protocols: [String]
we can detect them, yes, but I don't necessarily want to implement all protocols a thing conforms to in swift in the target language. For example, Hashable. I don't want to export that to Dart because Swift handles that already. It's not a user implemented protocol.

We only want to export user implemented protocols (I think).

2024-02-01 01:10 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        self.storedVariables = type.storedVariables
In swift a protocol can, it's a `var foo: Int { set get }`

2024-02-01 01:12 UTC, dvosscricut commented on integration-tests/TestAPI/Sources/TestAPI/Protocols.swift
> +}
ok

2024-02-01 01:14 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        return []
All I did for protocols in Dart was use an abstract class with method and property (set and/or get) definitions. Then the objects that use a protocol do an 'implements' of it.

I didn't seem to need any runtime anything for that, it's just declaring an interface. 

Since the actual object that implements the abstract class is where the runtime back and forth is.

2024-02-01 01:15 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +    struct Typealias {
perhaps not. This was a copy and paste job. Can certainly be cleaned up.

2024-02-01 01:17 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                    fragment.output("// \(method.name) not declared in abstract class because Dart does not support static method inheritance. It will only be put into the subclass that implements th
well, we can support it. We just don't put it in the abstract base class, we put it in the class that implements that abstract base class.

But you couldn't do "AbstractBaseClassName.staticMethodName()" in Dart. You'd have to do "ClassThatImplementsAbstractBaseClassName.staticMethodName()". 

If that's not useful we can prohibit static method and property exports for protocols.

2024-02-01 01:19 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/dart/lib/src/generated/TestMethodsProtocol.dart
> +abstract class TestMethodsProtocol {
implements is like a protocol, you have to implement ALL the properties and methods in the abstract base class.

extends is the inheritance. You can extend an abstract base class too. But if you extend a normal class you get the inheritance of the non overridden methods/properties.

You can only extend from one class i.e. inherit from one class.

But you can 'implement' many classes. So 'implements' with abstract base classes seems the way to go for Swift protocol definitions in Dart.

2024-02-01 01:23 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +    let constructor: Constructor
good point. removed.

2024-02-01 01:23 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +    struct Typealias {
good point. removed.

2024-02-01 01:25 UTC, dvosscricut commented on Sources/FishyJoesCore/FishyJoesContext.swift
> +        var translatedTypes = templateContext.types.protocols.compactMap { type -> TranslatedType? in
good point. fixed

2024-02-01 17:53 UTC, dvosscricut commented on Sources/FishyJoesCore/ExportAnnotation.swift
> +    let protocols: [String]
I noticed in your `cobbal/protocols` branch that you have a hard coded lists of protocols to exclude, including Hashable. However I believe it's more flexible to have the user declare what protocols they want exported, because the list of hard coded protocols may miss something to exclude. It's also easier to implement and maintain.

2024-02-01 21:23 UTC, cobbal commented on Sources/FishyJoesCore/ExportAnnotation.swift
> +    let protocols: [String]
Yeah. On second read that line isn't doing quite what I thought it was doing. I'm still on the fence if it's something we need to force the user to deal with. Seems like something we should be able to figure out for them.

2024-02-01 21:24 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        self.storedVariables = type.storedVariables
I believe that's a computed variable (at least in the protocol)

2024-02-01 21:34 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        self.storedVariables = type.storedVariables
For example, in the TestOptionalsProtocol, `flarp` shows up in the storedVariables in TranslatedProtocol.swift initializer.

In the TestProtocolClass in Protocols.swift, flare is implemented as a property, not a computed variable.

/// <!-- FishyJoes.export(flarp) -->
    public var flarp: String?

2024-02-01 21:39 UTC, dvosscricut commented on Sources/FishyJoesCore/ExportAnnotation.swift
> +    let protocols: [String]
It's more error prone to try and figure out for the user. We're already having the user export objects, methods, and properties, why not protocols as well?

That way, if the user's object conforms to some protocol we've never heard of that's an Apple Protocol, FishyJoes won't mess up on it saying it can't find it, because they won't export it. They'll only export the protocols that they define (and want to export).

2024-02-20 21:19 UTC, dvosscricut commented
archive for future reference

2024-02-20 21:19 UTC, closed without merging