AB#427207 Simple Protocol Support Export to Kotlin
cricut/FishyJoes pull request #173
Opened 2024-02-20 20:34 UTC by dvosscricut

AB#427207 Simple Protocol Support Export to Kotlin

Includes:

Default Implementations in Protocols

Excludes:

Static var/func support in Protocols

Protocol conformances to export to Fishy Joes are designated in export annotation in order to simplify implementation and allow user control of what Protocols are exported. The implementation is simplified because then FishyJoes doesn't have to somehow auto detect what Protocols to generate code for and what not to, which could be complicated and error prone.

Please find tests in `integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/ProtocolTests.kt`

2024-02-20 23:46 UTC, cobbal reviewed
Still working through this review, but commenting with what I have so far. The default implementations worked out much more cleanly than I thought it might.

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/Method.swift
> +        implemented: Bool = false
I would expect this to default to true. Aren't all methods for non-protocol types implemented? Maybe I don't understand what this boolean means. Either renaming, changing the default, or documentation could help, but I can't tell which.

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/Method.swift
> +                    name: isProtocolDef ? (parameter.asSource.starts(with: "_ ") ? "" : parameter.name) : parameter.name,
This feels a little odd having an empty string as the name. There might be a cleaner place to deal with whatever problem "name" was causing.

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/Method.swift
> +    func jniSignature(context: FishyJoesContext) -> String {
Probably a good extension method to have, but I think it would make more sense in KotlinTranslator.swift

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/Method.swift
> +        "(\(parameters.map { $0.type.name}.joined(separator: ", "))) -> \(returnType.name)"
This will be missing "async" and "throws" annotations.

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +    var conformances: Set<String> { get }
"String" may need to be changed in the future to be a full BetterType. In case some maniac decides to name protocols in 2 libraries the same thing. Then we'd need to be able to work with a (sometimes) package qualified name.

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +    let externalWitnessClassName: String
This field seems java-specific. If so, the name should reflect that (or it should just live entirely in the java-specific files)

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        let defaultMethods = methods.filter { $0.implemented }
would "isDefaultImplementation" be a more accurate name for "implemented"?

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                fragment.output("static let _javaWitness: JavaReference = { _javaWitness }()")
Is this an infinite loop?

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                    func gnr8GetterCode(fragment: SourceFragment) {
nope :)

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        fragment.outputBlock("return try! \(resolved.converterType.name).fromJava(") {
Hmm... we currently refuse to translate non-throwing function types because kotlin can't express them. Having all getters on all protocols need to be throwing might be a bigger user headache though. Is allowing them and then crashing at runtime if an exception happens better or worse long-term? @mstokercricut?

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                }
This is the logic that should also go in Method.swiftClosureSignature

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        if paramName.isEmpty {
This is where the empty name mentioned before comes back. I'm still not seeing the reason the name needed to be replaced with empty though. Maybe it comes up again later.

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        fragment.outputBlock("struct \(foreignProtocolType): \(sourceType.nonNamespacedName) {") {
nonNamespacedName should be used as sparingly as possible. The namespaced version should be preferred everywhere it doesn't break something.

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                    } else {
The organization surprises me a little here. I would expect the "else" of this block to look similar to the "if" block, only differing in the default fallback. One, however, uses a stored "Impl" closure property while the other one uses the JNI's call...Method. I suspect this means something could be cleaned up.

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                    fragment.output("jvalue(j: jlong(UInt(bitPattern: Box(value).retainedOpaque())))")
I think there was a convenience constructor added `jvalue(pointer:)` to make this less painful

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +        definedInType?.isExtension ?? false
This seems like it's either missing cases or is poorly named. Lots of non-default methods are implemented in extensions

2024-02-20 23:46 UTC, cobbal commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +            containingNamespace = resolved.converterType.name
This doesn't seem right. "containingNamespace" is supposed to refer to the namespace where the method is defined. converterType is a potentially different type in a potentially different module. Maybe it's being used wrong somewhere, but the fix should be at the usage.

2024-02-21 01:20 UTC, dvosscricut commented on Sources/FishyJoesCore/Method.swift
> +                    name: isProtocolDef ? (parameter.asSource.starts(with: "_ ") ? "" : parameter.name) : parameter.name,
it's for unnamed parameters in a method.

2024-02-21 01:20 UTC, dvosscricut commented on Sources/FishyJoesCore/Method.swift
> +        "(\(parameters.map { $0.type.name}.joined(separator: ", "))) -> \(returnType.name)"
good point

2024-02-21 01:21 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        fragment.outputBlock("struct \(foreignProtocolType): \(sourceType.nonNamespacedName) {") {
agreed. However it is required here, as TestAPI.AProtocol doesn't work.

2024-02-21 01:23 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +        definedInType?.isExtension ?? false
I think you're right. It should be a defined in extension AND is a protocol type. The bug probably just didn't get exposed by the current TestAPI.

2024-02-21 18:39 UTC, dvosscricut commented on Sources/FishyJoesCore/Method.swift
> +        implemented: Bool = false
good point. Should be named isInExtension.

I don't care if a method is in an extension or not generally, just when it's also a Protocol method, because a protocol method in an extension must be a default implementation. Since Methods are used in Protocol, Class, Struct, and Enum, I need to AND the isInExtension with isProtocol type to get if it's default implementation or not.

2024-02-21 18:40 UTC, dvosscricut commented on Sources/FishyJoesCore/Method.swift
> +    func jniSignature(context: FishyJoesContext) -> String {
I need to use it in TranslatedProtocol.swift when looping over protocol methods, so putting it on Method made more sense to me.

2024-02-21 19:00 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +    var conformances: Set<String> { get }
well, perhaps

2024-02-21 19:13 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        fragment.outputBlock("struct \(foreignProtocolType): \(sourceType.nonNamespacedName) {") {
actually, it does work here. I changed it to use `sourceType.name` here.

2024-02-21 19:22 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        fragment.outputBlock("struct \(foreignProtocolType): \(sourceType.nonNamespacedName) {") {
and in one other place. But the other places I tried broke stuff (in filenames), so I left those alone

2024-02-21 19:29 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                    } else {
I just noticed that `hasADefaultImplementationImpl` is never assigned. So the code always calls `_JavaAProtocol_sans_hasADefaultImplementation(wrapped: self).hasADefaultImplementation(x: x, y: y)`. That seems incorrect. 

Your instructive Animal example did not include calling JNI code.

Would you care to give an example of what the code should look like?

2024-02-21 21:31 UTC, cobbal requested changes
It's looking pretty good. I think there are still some important parts missing though

2024-02-21 21:31 UTC, cobbal commented on .swiftlint.yml
> +    - ./integration-tests/TestAPI-bindings/Sources/Generated/FishyJoes.generated.swift
This file should not exist, and is probably caused by print statements inside of FishyJoesCore. It should definitely not be excluded from lint.

2024-02-21 21:31 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        guard nonThrowingMethods.isEmpty else {
nit: a "guard let" is a good way to avoid needing to force-unwrap first

2024-02-21 21:31 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        let nonThrowingGetters = computedVariables.filter { !$0.`throws` && $0.writeAccess == AccessLevel.none.rawValue }
If I understand this logic, this allows for non-throwing getters, but only when we also have a non-throwing setter? I think any non-throws getter or setter will have the same problem.

2024-02-21 21:31 UTC, cobbal commented on integration-tests/TestAPI-bindings/Package.swift
> +            name: "CommonInterface",
This should be named "TestAPI_CommonInterface" for consistency. It also depends on FishyJoesCommonRuntime

2024-02-21 21:31 UTC, cobbal commented on integration-tests/TestAPI-bindings/Package.swift
> +            name: "CommonInterface",
Actually, it might be easier to make it not conform to `FishyJoesCommonRuntime.Converter` explicitly, but to just define the typealias. The protocol conformance doesn't really buy anything but documentation, and I'd rather not make `FishyJoesCommonRuntime` a public library.

2024-02-21 21:31 UTC, cobbal commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +        if method.isInExtension {
This should probably only apply to protocols

2024-02-21 21:31 UTC, cobbal commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +                        if name.isEmpty {
Removing the name seems to create more problems than it solves. This parameter had a perfectly good name, there's no reason to refer to it by a number instead.

2024-02-21 21:31 UTC, cobbal commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +                        if let nativeMethods = allMethods[resolved.converterType.name] {
I think `allMethods` should be keyed on the source type, not the converter type for reasons similar to the ones mentioned about "containingNamespace"

2024-02-21 21:31 UTC, cobbal commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +                                for (method, signature, cName, _) in normalMethods {
I would expect defaulted methods to still be in the witness class.

2024-02-21 21:31 UTC, cobbal commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +    func conform(_ kotlinClass: KotlinClass, to protoName: String, context: FishyJoesContext) {
Ideally, we'd use a BetterType instead of a String here, since protocols could come from any module

2024-02-21 21:31 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +                // For enums, we are doing a sealed class in Kotlin, not an interface, therefore there is no override on the methods.
Looking at the generated code for TestProtocolEnum.kt, I don't see that it conforms to kotlin's `AProtocol` at all. If that's fixed, can these overrides be turned back on?

2024-02-21 21:31 UTC, cobbal commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/ProtocolTests.kt
An important set of tests missing is implementing a swift-defined protocol in kotlin in the test suite. This should be passed to the swift side as an argument of type "AProtocol".

It should probably override one default method to make sure that both overriding works, and using the default implementation works.

I suspect the kotlin-overridden method will not currently be reachable from swift

2024-02-21 21:31 UTC, cobbal commented on Sources/FishyJoesJavaRuntime/Env.swift
> +        public func currentThreadEnv() throws -> Env {
I think the recent async work put a function like this inside of the Env type that more carefully deals with attaching threads. Namely the pair "acquireJVMThread" and "relinquishJVMThread". They should probably either be used directly or wrapped in a block-based convenience method.

2024-02-21 21:31 UTC, cobbal commented on Sources/FishyJoesJavaRuntime/JavaConverter.swift
> +    static var externalWitnessClass: jclass? { get }
nit: It would be nice not to put this in the JavaConverter protocol, and just have it be on the protocol types. I can't think of a reason we would need to know this dynamically.

2024-02-21 21:31 UTC, cobbal commented on Sources/FishyJoesJavaRuntime/JavaReference.swift
> +    }
This seems to duplicate the functionality in Env.swift

2024-02-21 21:31 UTC, cobbal commented on integration-tests/TestAPI-bindings/Sources/Generated/FishyJoes.generated.swift
I think I already mentioned it, but this file is garbage, and indicates print output or code fragments leaking without a proper source fragment set up.

2024-02-21 21:31 UTC, cobbal commented on integration-tests/TestAPI-bindings/Sources/Generated/JavaInterface/TestOptionalsProtocol+java.swift
This file (and some other protocol-related ones) are named inconsistently with the rest of the files in the folder. Most start with "TestAPI."

2024-02-21 21:31 UTC, cobbal commented on integration-tests/TestAPI-bindings/doIt.sh
> +cp .build/arm64-apple-macosx/debug/libTestAPI-java.dylib kotlin/src/generated/resources/mac/libTestAPI-java.dylib
This script should not be committed

2024-02-21 21:31 UTC, cobbal commented on integration-tests/TestAPI-bindings/kotlin/build.gradle.kts
> +            useJUnitPlatform()
I think this is a duplicate of line 65?

2024-02-21 21:31 UTC, cobbal commented on integration-tests/TestAPI-bindings/kotlin/build.gradle.kts
> +    testImplementation(kotlin("test"))
Adding an unversioned dependency is probably not a good idea. What new feature does this give?

2024-02-21 21:31 UTC, cobbal commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/MethodTests.kt
> +        print("a: $a")
These seem more like debugging code left in than tests. Are they still worth having?

2024-02-21 21:31 UTC, cobbal commented on scripts/compile-kotlin-native-runtime.sh
> +CONFIGURATION="${CONFIGURATION:-debug}"
This would turn on debug builds for all our releases. The intended way to get a debug build is to run `CONFIGURATION=debug ./scripts/compile-kotlin-native-runtime.sh`

2024-02-21 21:55 UTC, dvosscricut commented on .swiftlint.yml
> +    - ./integration-tests/TestAPI-bindings/Sources/Generated/FishyJoes.generated.swift
can you give me an example of where these print statements are? I searched for `print(` and only found a lot of comment out code in TypeSetup.swift

until I find out how to disable the generation of this file, SwiftLint will fail on it, unless it's excluded.

2024-02-21 21:56 UTC, dvosscricut commented on Sources/FishyJoesCore/Method.swift
> +        implemented: Bool = false
renaming done (and scoping to only use within SourceryProtocol type

2024-02-21 21:57 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +        definedInType?.isExtension ?? false
I renamed it and made sure to scope it with the AND is SourceryProtocol when using it to detect default implementations of protocol methods

2024-02-21 21:57 UTC, dvosscricut commented on Sources/FishyJoesJavaRuntime/Env.swift
> +        public func currentThreadEnv() throws -> Env {
this was ported from your protocol branch.

2024-02-21 21:58 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/Package.swift
> +            name: "CommonInterface",
this was ported directly from your protocol branch

2024-02-21 21:59 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/Sources/Generated/FishyJoes.generated.swift
example of such leaky code? I didn't find any print( statements in the code base.

2024-02-21 22:01 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/Sources/Generated/JavaInterface/TestOptionalsProtocol+java.swift
that they are. I was just trying to get it to work and the TestAPI prefix was messing it up in some of the generated files. But, to be consistent, should be fixed.

2024-02-21 22:03 UTC, dvosscricut commented on Sources/FishyJoesCore/Method.swift
> +        "(\(parameters.map { $0.type.name}.joined(separator: ", "))) -> \(returnType.name)"
async and throws supported now added

2024-02-21 22:04 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +            containingNamespace = resolved.converterType.name
well, perhaps. It made it work though, and was consistent with your protocols PR.

2024-02-21 23:23 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +                "integration-tests/TestAPI-bindings/Sources/Generated/FishyJoes.generated.swift"
Since this is already inside the TestAPI-bindings folder:
```suggestion
                "Sources/Generated/FishyJoes.generated.swift",
```

2024-02-22 19:14 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                    fragment.output("jvalue(j: jlong(UInt(bitPattern: Box(value).retainedOpaque())))")
indeed, updated to use jvalue(pointer:)

2024-02-22 19:15 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                    } else {
Hre is the example:

let java__AProtocolConverter__default_hasADefaultImplementation: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    jobject,
    Swift.Int.CType,
    Swift.Double.CType
) -> Swift.String.CType = { _javaEnv, _javaCompanionThis, _javaThis, x, y in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try Swift.String.toJava(
            try _JavaAProtocol_sans_hasADefaultImplementation(wrapped:
                try _AProtocolConverter.fromJava(_javaThis, env: _javaEnv)
            ).hasADefaultImplementation(
                x: try Swift.Int.fromJava(x, env: _javaEnv),
                y: try Swift.Double.fromJava(y, env: _javaEnv)
            ),
            env: _javaEnv
        )
    }
}

It's now implemented and pushed to remote

2024-02-22 19:15 UTC, dvosscricut commented on .swiftlint.yml
> +    - ./integration-tests/TestAPI-bindings/Sources/Generated/FishyJoes.generated.swift
ha ha ha, I must have made it when I had print statements while de3bugging and committed the file to source control, even though it shouldn't exist for normal code. It's deleted as part of CodeGen now.

2024-02-22 19:18 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        let nonThrowingGetters = computedVariables.filter { !$0.`throws` && $0.writeAccess == AccessLevel.none.rawValue }
It's if it does NOT throw but it is a getter i.e. the writeAccess is .none.

It's detecting any getters that do not throw, and if they exist it will do the police it's the law error.

2024-02-22 19:19 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        let nonThrowingGetters = computedVariables.filter { !$0.`throws` && $0.writeAccess == AccessLevel.none.rawValue }
I'll just do !$0.isMutable because it's the same thing and also more concise.

2024-02-22 19:21 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +        if method.isInExtension {
indeed!

I have amended to

if isProtocol,
           method.isInExtension {
            formals.append((name: "_javaCompanionThis", type: "jobject"))
        }

2024-02-22 19:21 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/doIt.sh
> +cp .build/arm64-apple-macosx/debug/libTestAPI-java.dylib kotlin/src/generated/resources/mac/libTestAPI-java.dylib
fixed!

2024-02-22 19:24 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/kotlin/build.gradle.kts
> +    testImplementation(kotlin("test"))
I was going to use some deep compare assertion equals function, but ended up not needing to use it.

I'll remove it.

2024-02-22 19:25 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/MethodTests.kt
> +        print("a: $a")
well, should probably have an assertion to check value, if it is to be left in

2024-02-22 19:28 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/MethodTests.kt
> +        print("a: $a")
fixed

2024-02-22 19:30 UTC, dvosscricut commented on scripts/compile-kotlin-native-runtime.sh
> +CONFIGURATION="${CONFIGURATION:-debug}"
ah, yes, that was when I wanted to make sure I got a debug build so I could step through swift code with lldb. I'll put it back.

2024-02-22 19:31 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/kotlin/build.gradle.kts
> +            useJUnitPlatform()
indeed, removed

2024-02-22 19:32 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        guard nonThrowingMethods.isEmpty else {
Since we already know it's not empty, then first must exist. I'm okay with using force unwrap in this case, because it has to be true, and avoids code that will never be executed in the proposed 'guard let first = nonThrowingMethods.first else {`'s block

2024-02-22 20:06 UTC, cobbal commented on integration-tests/TestAPI-bindings/Package.swift
> +            name: "CommonInterface",
And at the time it was consistent. Things have been renamed since then. Also, I'm pretty sure now that this is what's causing the parallel build failure.

2024-02-22 20:34 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/Package.swift
> +            name: "CommonInterface",
OK, it's now named "TestAPI_CommonInterface"

2024-02-22 22:42 UTC, dvosscricut commented on Sources/FishyJoesCore/Method.swift
> +                    name: isProtocolDef ? (parameter.asSource.starts(with: "_ ") ? "" : parameter.name) : parameter.name,
if the name property is empty then fishyjoes generates incrementingly named placeholder names such as "_1", "_2", and so forth.

But it really is an unnamed property, so I see it as appropriate to have an empty string for a name of something that's unnamed.

2024-02-22 22:48 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +    let externalWitnessClassName: String
very well, I shall add 'java' to the name

2024-02-22 22:51 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +    let externalWitnessClassName: String
and, I have!

2024-02-23 00:33 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                fragment.output("static let _javaWitness: JavaReference = { _javaWitness }()")
possibly. I should delete this since we're not trying to handle static methods and variables for protocols

2024-02-23 00:34 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                fragment.output("static let _javaWitness: JavaReference = { _javaWitness }()")
deleted

by the Cybermen

2024-02-23 00:38 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                }
good point. done (ding!).

2024-02-23 00:39 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        if paramName.isEmpty {
look at garply and sqpr functions to see why it's needed.

2024-02-23 00:39 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        if paramName.isEmpty {
well, it's not needed now that I discovered label

2024-02-23 16:15 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +            containingNamespace = resolved.converterType.name
@cobbal  Here is the same change in your Kotlin protocols PR:
https://github.com/cricut/FishyJoes/blob/f3b26ce3f0ae58fb238235f3c9d656eefeb5e4bf/Sources/FishyJoesCore/Translators/KotlinTranslator.swift#L21

<img width="1840" alt="Screenshot 2024-02-23 at 9 14 23 AM" src="https://github.com/cricut/FishyJoes/assets/48807612/f91d9a8b-647f-4642-88c0-f1c5135ec865">

2024-02-23 16:32 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +                                for (method, signature, cName, _) in normalMethods {
They are in the $Companion class because they exist in the companion object of the Kotlin side protocol

2024-02-23 16:35 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +                                for (method, signature, cName, _) in normalMethods {
The external witness implements the Protocol, which has the default implementation in the companion object. So, no need to override it on the ExternalWitness. It's simpler this way, because a default implementation method call on the ExternalWitness will call the companion object on the Protocol.

2024-02-23 16:36 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +    func conform(_ kotlinClass: KotlinClass, to protoName: String, context: FishyJoesContext) {
ideally yes. This is a straight port from your previous Kotlin protocols PR: https://github.com/cricut/FishyJoes/blob/f3b26ce3f0ae58fb238235f3c9d656eefeb5e4bf/Sources/FishyJoesCore/Translators/KotlinTranslator.swift#L541

2024-02-23 16:39 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +                // For enums, we are doing a sealed class in Kotlin, not an interface, therefore there is no override on the methods.
oh, good point. I suppose it should if it can, after all.

2024-02-23 16:50 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +                // For enums, we are doing a sealed class in Kotlin, not an interface, therefore there is no override on the methods.
ok, it's fixed now.

2024-02-23 17:13 UTC, dvosscricut commented on Sources/FishyJoesJavaRuntime/JavaConverter.swift
> +    static var externalWitnessClass: jclass? { get }
The externalWitness needs to be declared for all types that can be JavaConvertered, because the env.RegisterNatives in TypeSetup.swift needs it for any type that conforms to a protocol

2024-02-23 17:22 UTC, dvosscricut commented on Sources/FishyJoesJavaRuntime/JavaConverter.swift
> +    static var externalWitnessClass: jclass? { get }
I tried putting it in for only TranslatedProtocol in TypeSetup.swift, but got mysterious crashes in JNI unload i.e. TypeSetup at runtime (it built fine though).

2024-02-23 17:41 UTC, dvosscricut commented on Sources/FishyJoesCore/Method.swift
> +                    name: isProtocolDef ? (parameter.asSource.starts(with: "_ ") ? "" : parameter.name) : parameter.name,
as discussed, I have fixed this to preserve label and name and deal with the processing of it later, as the _ is the label indeed in the case that it's null.

2024-02-23 17:45 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                    } else {
as discussed priorly, the _sans_ call has been moved to the +javadecl.swift files and the _JavaAProtocol now always calls the JNI method. So if the _sans_ call fails to find a default implementation on the Swift side it will call the java side through the _JavaAProtocol in the Converter.

2024-02-23 17:45 UTC, cobbal requested changes
Looking pretty good. Tests are still failing.

This seems to be partly because the TestAPI_CommonInterface has an implicit dependency on TestAPI and FishyJoesCommonRuntime. The FishyJoesCommonRuntime dependency should be removed (delete ": Converter", and remove the import). The TestAPI dependency should be reflected in the Package.swift.

Even if the other languages don't yet support protocols, they should still compile (or it can't be merged).

I do want to get a look at the coverage report, because there are a lot of swift language features interacting in fiddly ways.

2024-02-23 17:45 UTC, cobbal commented on Sources/FishyJoesCore/FishyJoesContext.swift.orig
This shouldn't be committed. Possibly we should add ".orig" to gitignore, as it looks like it's an artifact of "git mergetool"

2024-02-23 17:45 UTC, cobbal commented on Sources/FishyJoesCore/Method.swift
> +        if returnType.name != "Void" {
A closure signature needs the arrow, but a function doesn't. I don't think this method is currently used.

2024-02-23 17:45 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        paramSigs.append("\(paramName): \(param.type.name)")
The name is a better name than trying to turn the label into a unique name. This also gets rid of all the ugly "+= 1"s
```suggestion
                        paramSigs.append("\(param.label.map { "$0 " } ?? "")\(param.name): \(param.type.name)")
```

2024-02-23 17:45 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        fragment.output("\(method.isThrowing ? "try " : "")wrapped.\(method.callName)(\(method.parameters.map { "\($0.name): \($0.name)" }.joined(separator: ", ")))")
label should be used here as well. Changing a label in one of the default methods to "_" would show the bug.

2024-02-23 17:46 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +                        if name.isEmpty {
labels/names have been fixed

2024-02-23 17:46 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/ProtocolTests.kt
I added `testProtocolKotlinImpl` in `ProtocolTests.kt` to do this now.

2024-02-23 20:08 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/Sources/Generated/FishyJoes.generated.swift
ah ha! it was past leaky code that has since been undone. the file needn't exist now!

2024-02-23 20:26 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/Sources/Generated/JavaInterface/TestOptionalsProtocol+java.swift
well, I just changed it to use the sourceType.name instead of sourceType.nonNameSpacedName for the protocol filenames, and it just worked. How nice!

fixed

2024-02-23 20:45 UTC, dvosscricut commented on Sources/FishyJoesJavaRuntime/Env.swift
> +        public func currentThreadEnv() throws -> Env {
The only currentThreadEnv() that is actually used is in JavaReference (used for javaWitness). 
So I just deleted these on Env.

2024-02-23 20:46 UTC, dvosscricut commented on Sources/FishyJoesCore/FishyJoesContext.swift.orig
good point. fixed

2024-02-23 20:48 UTC, dvosscricut commented on Sources/FishyJoesCore/Method.swift
> +        if returnType.name != "Void" {
it's not used! deleted!

2024-02-23 20:54 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        paramSigs.append("\(paramName): \(param.type.name)")
@cobbal  
except that the name on the protocol may be an empty string in the case of garply on TestMethodsProtocol:
/// <!-- FishyJoes.export(garply) -->
    func garply(_: String) throws -> String

Using the slightly corrected suggested code above `paramSigs.append("\(param.label.map { "\($0) " } ?? "")\(param.name): \(param.type.name)")`

results in this erroroneus code in TestAPI.TestMethodsProtocol+java.swift

    public func garply(: String) throws -> String {

when it needs to be

 public func garply(_ someAutoGeneratedIncrementingName: String) throws -> String {

2024-02-23 20:56 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        paramSigs.append("\(paramName): \(param.type.name)")
also, names in protocols shouldn't be used, even if they exist. Only labels should. The name (internal parameter name) should be left to the implementer of the protocol. although I believe I do use the internal name if declared on a protocol anyway with TestOptionalsProtocol spqr(_ pipe: AssociatedDataEnum). oh well. I guess I should fix that.

// for protocols, only look at the label (external parameter name), don't use the internal parameter name i.e. name)

In summary, protocols only should declare external interfaces, not any internal interface deets, even though they can (though I don't think it's enforced). Agree?

In any case, in the garply case rather, the name is empty and the label is "_" so we have to come up with auto generated names for this case _1, _2, _3, and so forth.

2024-02-23 21:02 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        fragment.output("\(method.isThrowing ? "try " : "")wrapped.\(method.callName)(\(method.parameters.map { "\($0.name): \($0.name)" }.joined(separator: ", ")))")
ah, good catch. I'll make one of the labels of the default implementation test methods be "_" to catch this.

2024-02-23 22:23 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        fragment.output("\(method.isThrowing ? "try " : "")wrapped.\(method.callName)(\(method.parameters.map { "\($0.name): \($0.name)" }.joined(separator: ", ")))")
okay, I made hasADefaultImplementation2 have both unnamed label/name combos, _ name: Type and _: Type to verify this. It's working now for this method signature: `func hasADefaultImplementation2(_ a: String, b: Bool, _: Double) throws -> Double`

2024-02-23 22:43 UTC, dvosscricut commented on Sources/FishyJoesJavaRuntime/JavaReference.swift
> +    }
This one is for the javaWitness on the protocol, which needs the vm that the Env doesn't have. And also needs the currentThreadEnv

2024-02-24 01:11 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +            containingNamespace = resolved.converterType.name
when I make those 2 recommended converterType to sourceType changes, I get these droppedMethods error:

Users/dvoss/Downloads/code/FishyJoes/Sources/FishyJoesCore/Translators/KotlinTranslator.swift:376: methods for ["TestAPI.TestMethodsProtocol", "TestAPI.AProtocol", "TestAPI.TestOptionalsProtocol", "_TestPropertiesProtocolConverter"] were never set up! Probably a bug.

2024-02-24 01:54 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +            containingNamespace = resolved.converterType.name
also, could we just combine the into the same file. So now we'd just have _AProtocolConverter.swift with all the conversion JNI hookup and to/fromJava stuff all in one file?
 
it seems much less confusing to me that way.

Though maybe the purpose of the separate files it because they are generated in separate functions and we don't want to have the pain of passing the same SourceFragment or matching up between arrays of SourceFragments between the functions. Is that why they're split up?

If that is indeed the case, may I change the name of the +java.swift files to have the converterType.name rather than the sourceType.name? It seems a more logical grouping of for example _AProtocolConverter+javadecl.swift, _AProtocolConverter+java.swift, and _AProtocolConverter.swift rather than having _AProtocolConverter+javadecl.swift, TestAPI.AProtocol+java.swift, and _AProtocolConverter.swift

(as Test.AProtocol+java.swift is actually implementing the fromJava/toJava functions i.e. the conversion functions.

well, I've implemented that now on the PR, swift files containing converting to/fromJava related code are now named under the converterTypeName.

I'll see what feedback you have for me on this decision of mine.

2024-02-27 17:50 UTC, cobbal requested changes

2024-02-27 17:50 UTC, cobbal commented on Sources/FishyJoesCore/Translators/DartTranslator.swift
> +                }
A very strange stub

2024-02-27 17:50 UTC, cobbal commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +                selfExpression = converterNamespace
It probably doesn't matter, but this is incorrect. "Self" is containingNamespace, not the converter

2024-02-27 17:50 UTC, cobbal commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +        fragment.output("// Generated by FishyJoes for `\(converterNamespace).\(method.name)`")
Incorrect documentation. The method is "AProtocol.foo", not "AProtocolConverter.foo"

2024-02-27 17:50 UTC, cobbal commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +                        fragment.outputBlock("try \(destinationRootFilename).mutateJava(_javaThis, env: _javaEnv) { value in", closeWith: "}") {
Why are we calling methods on a file name?

2024-02-27 17:50 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +            context.kotlinTranslator.allMethods[converterType.name, default: []].append(
As mentioned in a previous review:

> I think allMethods should be keyed on the source type, not the converter type for reasons similar to the ones mentioned about "containingNamespace"

Methods are not on the converter. The converter is only for fromJava and toJava. The methods are part of the source type.

2024-02-27 17:50 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        paramSigs.append("\(paramName): \(param.type.name)")
`name` is a much better name than "\_2" will ever be. "garply(\_ str: String)" is infinitely better than "garply(\_ someAutoGeneratedIncrementingName: String)"

2024-02-27 17:50 UTC, cobbal commented on Sources/FishyJoesJavaRuntime/JavaReference.swift
> +    public func currentThreadEnv() throws -> Env {
This function should not be added. The async work added in a similar function that keeps better track of the attached threads. (`acquireJVMThread`/`relinquishJVMThread`)

2024-02-27 18:03 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/DartTranslator.swift
> +                }
:)

2024-02-27 19:19 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/DartTranslator.swift
> +                }
fixed

2024-02-27 19:22 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +        fragment.output("// Generated by FishyJoes for `\(converterNamespace).\(method.name)`")
fixed

2024-02-27 19:22 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +                selfExpression = converterNamespace
fixed

2024-02-27 19:28 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +                        fragment.outputBlock("try \(destinationRootFilename).mutateJava(_javaThis, env: _javaEnv) { value in", closeWith: "}") {
good question. It's sourceTypeName now

2024-02-27 19:29 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +            context.kotlinTranslator.allMethods[converterType.name, default: []].append(
It's sourceTypeName now. except in the place it must be converterTypeName

but the allMethods is always keyed off of sourceTypeName now.

2024-02-27 19:31 UTC, dvosscricut commented on Sources/FishyJoesJavaRuntime/JavaReference.swift
> +    public func currentThreadEnv() throws -> Env {
how would the acquire/relinquishJVMThread functions be used in this code example?

static var _fooGetMethodID: jmethodID?
    public var foo: String {
        get throws {
            let env = try _javaWitness.currentThreadEnv()
            return try Swift.String.fromJava(
                env.CallObjectMethod(_javaWitness.object, Self._fooGetMethodID),
                env: env
            )
        }
    }

2024-02-27 19:36 UTC, dvosscricut commented on Sources/FishyJoesJavaRuntime/JavaReference.swift
> +    public func currentThreadEnv() throws -> Env {
would this work?

```
static var _fooGetMethodID: jmethodID?
    public var foo: String {
        get throws {
            let env = try Env.acquireJVMThread(on: _javaWitness.vm)
            defer {
                try? Env.relinquishJVMThread(on: _javaWitness.vm)
            }
            return try Swift.String.fromJava(
                env.CallObjectMethod(_javaWitness.object, Self._fooGetMethodID),
                env: env
            )
        }
    }
```

2024-02-27 19:37 UTC, dvosscricut commented on Sources/FishyJoesJavaRuntime/JavaReference.swift
> +    public func currentThreadEnv() throws -> Env {
or perhaps this?

```
static var _fooGetMethodID: jmethodID?
    public var foo: String {
        get throws {
            let env = try Env.acquireJVMThread(on: _javaWitness.vm)
            let fromJava = try Swift.String.fromJava(
                env.CallObjectMethod(_javaWitness.object, Self._fooGetMethodID),
                env: env
            )
            try Env.relinquishJVMThread(on: _javaWitness.vm)
            return fromJava
        }
    }
```

2024-02-27 20:46 UTC, dvosscricut commented on Sources/FishyJoesJavaRuntime/JavaReference.swift
> +    public func currentThreadEnv() throws -> Env {
acquire and relinquish have been implemented

2024-02-27 20:58 UTC, cobbal approved these changes

2024-02-27 21:59 UTC, merged

2024-05-14 03:57 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +    var conformances: Set<String> { get }
@cobbal  I made an Azure DevOps ticket for it here: https://cricut.visualstudio.com/Cricut/_workitems/edit/478509

2024-05-14 03:58 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/KotlinTranslator.swift
> +    func conform(_ kotlinClass: KotlinClass, to protoName: String, context: FishyJoesContext) {
https://cricut.visualstudio.com/Cricut/_workitems/edit/478509 ticket to do this