Dvoss/dart tart
cricut/FishyJoes pull request #180
Opened 2024-03-12 01:07 UTC by dvosscricut

Implement Simple Protocol Support for Dart

2024-03-13 21:48 UTC, cobbal requested changes

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesCore/BetterType.swift
> +    var module: String? {
This seems incomplete. Generics have modules, I think void has a module (`Swift`).

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesExecutionHelper/main.swift
> +      CommandLine.arguments[3] == "--xcode-debug" {
This is too specific to your configuration. Better would be to just not pass in the `argument["stderrFifo"]` when calling from xcode

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +           !module!.isEmpty {
There are a quite a few issues with this. Too many force unwraps, weird questions about empty module names. Most importantly, this condition isn't ever failed. module will always (I think) end up being "\\(context.module)_CommonInterface"

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +        }
I don't think this belongs in TranslatedStruct. There should be nothing specific to structs about how methods are set up

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +                    if storedVar.isPubliclyWritable {
Since a field of a struct can be mutated by a mutating method, even if the setter isn't public, I think "isPubliclyWritable" is the wrong condition.

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +        sourceType.name.mangled
This will affect lots of things. Why was the change needed?

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesCore/Translators/IotaTranslator.swift
> +                                fragment.outputBlock("try _Iota\(definedInName)_sans_\(method.callName)(wrapped:", closeWith: ")") {
Are the "sans" wrapper structs language-specific? It might be possible to move them into the common interface and reduce duplication.

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesCore/Translators/IotaTranslator.swift
> +                            if method.isInExtension,
Like with kotlin, this should be guarded by being a protocol extension, not just an extension

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +        let isInExtension: Bool
Is this really a property of a dart method?

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +           let conformance = conformances.first {
This list was sorted alphabetically. First is probably not the correct one.

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +            peekTypeName = "\(module.name).\(conformance)"
"module" is the module of the conforming class, not the module of the protocol

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                    toStringImpl(fields: fields, fragment: fragment)
What do conformances have to do with toString?

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +        let (fields, methods) = KotlinClass.separate(fieldsAndMethods: fieldsAndMethods)
This pattern keeps repeating. Separate, then just pass both parts anyway. I don't see what the benefit is.

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesCore/Translators/DartTranslator.swift
> +            let definingDartClass = nativeMethod.definingDartClass + (nativeMethod.isInExtension ? "_DefaultImplementations" : "")
isInExtension is a terrible name for this variable. Is it about defaulted implementations or extensions? Only in some cases do they align.

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +        if !(self is DartProtocolClass) {
This is a pretty bad use of inheritance. If the fields shouldn't be output in this manner, don't put them into the superclass's "fields" field.

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +        if !(self is DartProtocolClass) {
Or better yet, The fields that are output in the normal method should be dealt with here, but the fields that are output in a special manner should just go into a field that DartProtocolClass has/deals with.

2024-03-13 21:48 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +            if !(self is DartProtocolClass) ||
Again, a superclass should not be testing if it's a subclass. Just use normal overriding mechanisms.

2024-03-13 21:48 UTC, cobbal commented on integration-tests/TestAPI-bindings/doIt.sh
Still shouldn't be committed

2024-03-13 21:53 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        }
These 2 loops could be combined

2024-03-13 21:58 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        fragment.outputBlock("try env.check { exn in _\(computedVar.name)Setter[env](", closeWith: ")}") {
This doesn't seem right. mutation shouldn't cause writing of computed variables

2024-03-13 21:59 UTC, dvosscricut commented on Sources/FishyJoesExecutionHelper/main.swift
> +      CommandLine.arguments[3] == "--xcode-debug" {
as you wish

2024-03-13 22:01 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +           !module!.isEmpty {
sourceType.module is optional

boolean expression in if statement can be false and module can be nil

2024-03-13 22:05 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +        }
dartSetupDelegates exists in the various translated types and do vary in their format between Enum, Protocol, Struct (compare TranslatedEnum+dart.swift starting on line 2 with TranslatedProtocol.swift line starting on line 118. TranslatedType the parent class has a return empty array implementation of this method. If it doesn't belong in TranslatedType subclasses, where should it belong?

2024-03-13 22:06 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +                    if storedVar.isPubliclyWritable {
not in the foreign interface. We only allow getters from dart to swift access for properties/struct fields. Because Swift only supports 'get throws', but does not support 'set throws'

2024-03-13 22:07 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +        let (fields, methods) = KotlinClass.separate(fieldsAndMethods: fieldsAndMethods)
The benefit is using common code, whereas before the code was duplicated inside the various subclasses of Dart/KotlinClass's init methods, such as DartProductClass, DartEnumClass, and DartProtocolClass.

Also, it's clearer to reason about separated fields and methods at the module boundaries say while debugging than it is with them combined.

2024-03-13 22:11 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/DartTranslator.swift
> +            let definingDartClass = nativeMethod.definingDartClass + (nativeMethod.isInExtension ? "_DefaultImplementations" : "")
It's the only information I have from Sourcery to determine if a method is a default implementation in a protocol or not. Sourcery named it "isExtension" in SourceryRuntime/Sources/AST/Type.swift . Would that be a better name?

Do you have another name suggestion?

Also, what other criteria do you know of that I could use to detect if a method is a default implementation? If it's in an extension and it's a protocol we're processing, does it not have to be a default implementation?

2024-03-13 22:13 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +        if !(self is DartProtocolClass) {
This is in a computed variable 'nativeMethods'. If it were in a function body I'd agree with you. But the fields need to still exist to output to the ExternalWitness instead of the ProtocolClass. I can't remove them, I need them both to exist, and to filter here. Though I could just not use nativeMethods and use something else for Protocols?

2024-03-13 22:14 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +            if !(self is DartProtocolClass) ||
I think I've read about superclasses knowing about subclasses as a bad practice. I'll have to think about this one.

2024-03-13 22:26 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/doIt.sh
ha ha, how funny that I did that again!

2024-03-13 22:29 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/doIt.sh
fixed

2024-03-13 22:31 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        }
do you mean put it all on one line? I think that makes it less readable, and more in line with the parody of swiftness that is put as much as you can on one line with as many chained maps as possible.

2024-03-13 22:33 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        }
I put it on one line in case that's what you want. If it's not what you want, please give me a code example to help me understand what you'd like. thx!

2024-03-13 22:39 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        fragment.outputBlock("try env.check { exn in _\(computedVar.name)Setter[env](", closeWith: ")}") {
it's just named wrong. I'll just call it "fields" instead.

2024-03-13 22:43 UTC, dvosscricut commented on Sources/FishyJoesCore/BetterType.swift
> +    var module: String? {
good point.

'tis remedied now

2024-03-13 22:45 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +           !module!.isEmpty {
I can avoid using force unwraps at the cost of brevity though

2024-03-13 22:49 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +           !module!.isEmpty {
which I have now pushed to remote, it's now one line longer, not too bad. Is that what you wanted?

2024-03-13 23:01 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +        let (fields, methods) = KotlinClass.separate(fieldsAndMethods: fieldsAndMethods)
As a silly example, take a module with 10 separate input arguments. Then, instead of passing all 10 input arguments separately, instead combine them in a mass AOrBOrCOrD etc. type enum, then pass that one enum as one argument into the module, then inside the init method of the module, extract all the properties out again. I think you'll agree that passing 10 separate input arguments into the module is easier to reason about.

Add to that AOrBOrCOrD object extracting code being duplicated inside of multiple different module's init methods, and it adds unnecessary code duplication to the list of problems with this approach

2024-03-13 23:09 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +        }
For example, the `dartSetupParameters` function implementation in "TranslatedReference.swift" (hereafter abbreviated as [TR]) differs from the one in "TranslatedStruct.swift" (Hereafter abbreviated as [TS] in several notable ways:

1)  [TR] has one single hardcoded ForeignSetupParameter, with a single stored variable (the reference), and nothing else in it, and the constructor ffi function name is "ffi_new".
[TS] has a constructor with potentially many storedVariable inputs that can vary, and the constructor ffi function name is "ffi_constructor"

2) [TR] has no other storedVariables than the reference to the swift object.
[TS] can have many storedVariables as well as have methods.

[TE] (TranslatedEnum) doesn't override dartSetupParameters at all, using the default implementation of returning an empty array defined in TranslatedType.swift.

Many other differences can be discovered upon inspection.

2024-03-13 23:19 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +        sourceType.name.mangled
It's to name the ffi stuff by the Protocol's name instead of the ProtocolConverter's name. Because the ProtocolConverter only exists on the Swift side, on the Dart side it's just the Protocol or ExternalWitness. There is no ProtocolNameConverter.dart file on the Dart side.

When I do need the converter name such as in type_setup.dart when hooking up external functions to the ProtocolConverter (such as for Loader.shared.once("setup_TestAPI_CommonInterface._AProtocolConverter", () {/'TestAPI_Structs_ReferenceStruct_setup', I grab it explicitly from the type with converterType. Otherwise the sourceType.name should be what it is normally for the mangled name

2024-03-13 23:21 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/DartTranslator.swift
> +            let definingDartClass = nativeMethod.definingDartClass + (nativeMethod.isInExtension ? "_DefaultImplementations" : "")
How about I call it "isDefaultImplementation" instead? It is only used in TranslatedProtocol, and is hard coded to false for other TranslatedTypes.

I believe if a method is in a Protocol and also in an extension, then it must be a defaultImplementation.

2024-03-13 23:26 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/DartTranslator.swift
> +            let definingDartClass = nativeMethod.definingDartClass + (nativeMethod.isInExtension ? "_DefaultImplementations" : "")
I believe I'll still need "isExtension" from Sourcery, but I could make a computed property where isDefaultImplementation is based on the Method's definedInType and could only be true if the definedInType is a Protocol type.

2024-03-14 00:22 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/DartTranslator.swift
> +            let definingDartClass = nativeMethod.definingDartClass + (nativeMethod.isInExtension ? "_DefaultImplementations" : "")
ok, I made an isDefaultImplementation on property. The definedInType way didn't work so I used the isProtocol method instead

2024-03-14 00:23 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/IotaTranslator.swift
> +                            if method.isInExtension,
good point, fixed now

2024-03-14 00:25 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/IotaTranslator.swift
> +                                fragment.outputBlock("try _Iota\(definedInName)_sans_\(method.callName)(wrapped:", closeWith: ")") {
no, they aren't unique, the Swift code for the Java sans and the Iota sans are identical except for the struct name. I could indeed move them to a common place.

2024-03-14 00:26 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/IotaTranslator.swift
> +                                fragment.outputBlock("try _Iota\(definedInName)_sans_\(method.callName)(wrapped:", closeWith: ")") {
What common place/file would you like? +iota-type/+java-type are out since the rest of the files are different between iota and java. same for +iota-methods/+java-methods.

Perhaps in TestAPI_CommonInterface ? As in TestAPI_CommonInterface._AProtocolConverter?

2024-03-14 00:27 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +        let isInExtension: Bool
not anymore! It's now "isDefaultImplementation"

2024-03-14 00:29 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +        if !(self is DartProtocolClass) {
I think the more proper way to do it would be to subclass override then nativeMethods In DartProtocolClass and leave the others as a default. I'll do that then, I think.

2024-03-14 00:33 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +        if !(self is DartProtocolClass) {
done (ding!)

2024-03-14 00:34 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +            if !(self is DartProtocolClass) ||
also now done (ding!)

2024-03-14 00:44 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                    toStringImpl(fields: fields, fragment: fragment)
good catch. That's leftover debug code.

It's okay to toString for reference and public constructors. It's okay to display foreign fields. They just need different inputs, fields for reference constructor and storedFields for public constructor.

2024-03-14 00:44 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartClass.swift
> +                    toStringImpl(fields: fields, fragment: fragment)
fixed (ding!)

2024-03-14 16:05 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/IotaTranslator.swift
> +                                fragment.outputBlock("try _Iota\(definedInName)_sans_\(method.callName)(wrapped:", closeWith: ")") {
OK! I did it! I put it in TestAPI_CommonInterface.

Code duplication: reduced!

2024-03-14 21:35 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +           !module!.isEmpty {
sourcetype.module gets set earlier this function (line 31). It's always context.module.

2024-03-14 21:44 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        }
The methods are being split into normalMethods and defaultMethods, then each is being looped over in nearly identical ways. Instead, just loop over all methods and test inside the loop

2024-03-14 21:51 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +           !module!.isEmpty {
not necessarily, if you look inside the BetterType init (line 148), it's possible for module to be nil as returned from this initializer.

2024-03-14 21:59 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        }
oh, I see it now. good point.

2024-03-14 22:01 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        }
ok, it's fixed now, but I'll wait to push to remote until you're done reviewing (please let me know, thx!)

2024-03-14 22:13 UTC, cobbal commented on Sources/FishyJoesExecutionHelper/main.swift
> +      CommandLine.arguments[3] == "--xcode-debug" {
Not quite what I had in mind. The command line `fishy-joes` passes an argument to sourcery named "stderrFifo" to tell it to redirect the output. You have added a new command in a different place to override that behavior and not redirect the output. The simpler solution is to just find where you have xcode passing in the sourcery data, and just remove the "stderrFifo" argument from it. No need for this new "noStdErrFifo" variable.

2024-03-14 22:20 UTC, dvosscricut commented on Sources/FishyJoesExecutionHelper/main.swift
> +      CommandLine.arguments[3] == "--xcode-debug" {
tricked again! OK I'll change it.

2024-03-14 22:25 UTC, dvosscricut commented on Sources/FishyJoesExecutionHelper/main.swift
> +      CommandLine.arguments[3] == "--xcode-debug" {
oh, wait, I do need it there to let the fishy joes emoji executable know if it's being called from the command line or from Xcode.

Sourcery is not rerun when running from Xcode, as I'm running just the emoji fishy joes executable.

2024-03-14 22:59 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +                    if storedVar.isPubliclyWritable {
Given a swift struct like:

```
/// <!-- FishyJoes.export(Counter) -->
struct Counter {
    public private(set) var count: Int = 0
    /// <!-- FishyJoes.export(tick) -->
    mutating func tick() { count += 1 }
}
```

The real "count" variable lives on the dart side, but the "tick" function lives on the swift side. To call "tick" from dart

1. count is read from the dart "Counter" object
2. a new swift "Counter" is created with with same count
3. The mutating method "tick" is then run on the swift counter
4. The changes are copied back to the original dart "Counter"
 
In order to do step 4, an ffi setter is needed for count. Even though it's not publicly writable.

2024-03-14 23:20 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +                    if storedVar.isPubliclyWritable {
good point

2024-03-15 14:35 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +                    if storedVar.isPubliclyWritable {
ok, fixed now.

2024-03-15 14:42 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +        let (fields, methods) = KotlinClass.separate(fieldsAndMethods: fieldsAndMethods)
Additionally, for DartProtocolClass, I can remove the init override entirely because it matches the DartClass init. Code removal and less duplication == win!

2024-03-18 16:07 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +        }
There's nothing about adding protocols that should cause only structs to start registering their methods differently. If you delete this block all the tests still pass, so what was it doing?

2024-03-18 20:57 UTC, cobbal approved these changes
Once the struct-method-typedef bit is removed, this looks good to merge

2024-03-19 00:29 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +        }
I was thinking of a potential case that I don't have a test case for yet where somehow a method must need to be called on a struct in that way. But it wouldn't work right now anyways because the typedef isn't even hooked up to anything! ha ha! well, perhaps on a future PR then. 

I made this Excalidraw diagram of the hasADefaultImplementation calls to start with, since I need it for reference to perhaps reason about this potential theoretical test case.

![hasADefaultImplementationDartSwiftCalls](https://github.com/cricut/FishyJoes/assets/48807612/2ee5a0a6-5547-4799-a3dc-9baa1ad0818e)

2024-03-19 00:56 UTC, merged