Add Async methods and computed variables in Protocols support to Kotlin
cricut/FishyJoes pull request #198
Opened 2024-03-28 22:21 UTC by dvosscricut

Add Async methods and computed variables in Protocols support to Kotlin

2024-03-29 21:43 UTC, cobbal requested changes
Looks pretty good. The escapingName adds a lot of stuff, but I think most of it can be removed after fixing "name"

2024-03-29 21:43 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedFunction.swift
> +                isThrowing: false
All function types we export should be marked throwing. Since in js/kotlin/c#/dart all functions are throwing

2024-03-29 21:43 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        let asyncMethods = methods.filter { $0.isAsync }
This feels like a combinatoric explosion. What about things that are both default and async?

2024-03-29 21:43 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +            let doExternalCompanionClass = !defaultMethods.isEmpty ||
Should probably just always do the companion. The compiler doesn't mind if it's empty, and it makes our logic simpler.

2024-03-29 21:43 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +            let doExternalCompanionClass = !defaultMethods.isEmpty ||
In general in code-gen, I like to keep the 0 cases consistent with the many cases, and not filter them out. Sometimes it's not possible depending on how aggressive downstream compilers are.

2024-03-29 21:43 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/DartProtocolClass.swift
> +                }
Probably wasn't meant to be committed.

2024-03-29 21:43 UTC, cobbal commented on integration-tests/TestAPI/Sources/TestAPI/Protocols.swift
> +public struct TestAsyncForeignSideFunctionsStruct: TestAsyncFunctions {
I'm not sure this is testing anything fundamental to protocols. We're already testing that kotlin functions can be passed and called in other places.

2024-03-29 21:43 UTC, cobbal commented on Sources/FishyJoesCore/BetterType.swift
> +            return "(\(args.map(\.escapingFunctionsName).joined(separator: ", ")))\(isAsync ? " async" : "")\(isThrowing ? " throws" : "") -> \(ret.name)"
I think I see what you're trying to do with these changes, and I think it can be cleaned up significantly:

```
    var name: String {
        switch self {
        case let .named(name):
            return name.globalName
        case .tuple(let elements):
            return "(" + elements.map {
                if Int($0.label) == nil {
                    return "\($0.label): \($0.type.name)"
                } else {
                    return $0.type.name
                }
            }.joined(separator: ", ") + ")"
        case .void:
            return "Void"
        case let .function(args, ret, isAsync, isThrowing):
            return "(\(args.map(\.escapingName).joined(separator: ", ")))\(isAsync ? " async" : "")\(isThrowing ? " throws" : "") -> \(ret.name)"
        case .generic(let base, let args):
            return "\(base.name)<\(args.map(\.name).joined(separator: ", "))>"
        case .selfType:
            return "Self"
        }
    }

    var nonNamespacedName: String {
        switch self {
        case let .named(name):
            return name.name
        default:
            return name
        }
    }

    var escapingName: String {
        switch self {
        case .function:
            return "@escaping \(name)"
        default:
            return name
        }
    }
```

2024-03-29 21:43 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                fragment.output("var \(field.name): \(fieldType)")
Any changes involving actualTypeName shouldn't be needed.

2024-03-29 21:43 UTC, cobbal commented on Sources/FishyJoesNodeRuntime/NodeReference.swift
> +    public private(set) var env: NAPI.Env
This should not be stored, as it's thread-specific (sometimes)

2024-03-29 22:21 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedFunction.swift
> +                isThrowing: false
whoakay

2024-03-29 22:24 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        let asyncMethods = methods.filter { $0.isAsync }
oh, I should add a test case for that.

I don't have an async defaultMethod test case (yet).

2024-03-29 22:24 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +            let doExternalCompanionClass = !defaultMethods.isEmpty ||
ok, always do the companion then

2024-03-29 22:25 UTC, dvosscricut commented on Sources/FishyJoesNodeRuntime/NodeReference.swift
> +    public private(set) var env: NAPI.Env
luckily I don't need it right now, just when I try to do the nodeWitness will I might need it.

2024-03-29 22:36 UTC, dvosscricut commented on Sources/FishyJoesCore/BetterType.swift
> +            return "(\(args.map(\.escapingFunctionsName).joined(separator: ", ")))\(isAsync ? " async" : "")\(isThrowing ? " throws" : "") -> \(ret.name)"
thanks! done.

2024-03-29 22:39 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                fragment.output("var \(field.name): \(fieldType)")
I think this was a remnant of from before when I didn't have escaping name set up.

2024-03-29 22:48 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                fragment.output("var \(field.name): \(fieldType)")
ok, now that the better.name puts the @escaping in already I don't need the actualTypeName anymore

2024-03-29 22:54 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        let asyncMethods = methods.filter { $0.isAsync }
things that are both default and async will still get put in the companion, they'd just be under the asyncMethods loop rather than the defaultMethods loop. Perhaps I should have 4 cases to be more clear: defaultAsync, default, normalAsync, normal. 2 input bits, 4 output combinations

2024-03-29 23:10 UTC, dvosscricut commented on integration-tests/TestAPI/Sources/TestAPI/Protocols.swift
> +public struct TestAsyncForeignSideFunctionsStruct: TestAsyncFunctions {
Other places are not protocols though

Since protocols are new and different to what currently exists in terms of tests, I believe we ought to exercise this in tests specifically for async functions in protocols passed in from Kotlin.

It also helped me learn the fancy dance of closures in Kotlin tests though.

2024-03-30 00:27 UTC, dvosscricut commented on integration-tests/TestAPI/Sources/TestAPI/Protocols.swift
> +public struct TestAsyncForeignSideFunctionsStruct: TestAsyncFunctions {
I found some significant CodeGen bugs through this scenario, therefore I believe it should stay to make sure they stay fixed.

2024-03-30 03:23 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/DartProtocolClass.swift
> +                }
indeed!

2024-04-01 23:13 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +        let asyncMethods = methods.filter { $0.isAsync }
Ok, I put the test case in for the default implementation async methods in protocol. And it found more bugs! So good thing it's tested now!

2024-04-02 18:04 UTC, cobbal requested changes
Couple fairly minor issues. Coverage seems a little low. There's not really a concrete percentage we go for in this repo, but it might be worth looking at the report and seeing if you're seeing what you expect to be covered.

2024-04-02 18:04 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +                    fragment.output(" = \(body)\(method.returnType.toKotlinType)\(method.isSuspend ? ".await()": "")")
This should probably follow the same logic for line 173. Async UInt methods will probably fail to typecheck

2024-04-02 18:04 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/KotlinInterface.swift
> +                        fragment.outputBlock("fun \(method.name)(", newLineTerminated: false) {
This name should probably get a prefix to avoid ambiguity with the non-static method. Differing only by static-ness and number of arguments feels like a recipe for future developer confusion.

2024-04-02 19:39 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/KotlinClass.swift
> +                    fragment.output(" = \(body)\(method.returnType.toKotlinType)\(method.isSuspend ? ".await()": "")")
done

2024-04-02 19:43 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/KotlinInterface.swift
> +                        fragment.outputBlock("fun \(method.name)(", newLineTerminated: false) {
it has the prefix "_default". I updated the code to check for "_default" instead of just "_"

2024-04-02 19:47 UTC, dvosscricut commented
> Couple fairly minor issues. Coverage seems a little low. There's not really a concrete percentage we go for in this repo, but it might be worth looking at the report and seeing if you're seeing what you expect to be covered.

Sonar cloud doesn't seem to run the Kotlin tests to determine code coverage. It's saying exercise0-6 are uncovered, even though I explicitly cover them in the ProtocolTests.kt. I don't think Sonar cloud knows how to run Kotlin tests to determine if Swift code is covered.

![Screenshot 2024-04-02 at 1 46 19 PM](https://github.com/cricut/FishyJoes/assets/48807612/7c190d90-0d0e-448d-89a8-164d2b11def9)


It is the case though for other targets such as Dart and CSharp and Node that it's complaining about, but those tests will come later.

2024-04-02 20:54 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/KotlinInterface.swift
> +                        fragment.outputBlock("fun \(method.name)(", newLineTerminated: false) {
decided, for the deferred wrapper companion object functions we should use the prefix "_deferred"

2024-04-02 22:38 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/KotlinInterface.swift
> +                        fragment.outputBlock("fun \(method.name)(", newLineTerminated: false) {
done (ding!)

2024-04-02 22:43 UTC, cobbal approved these changes

2024-04-02 22:43 UTC, cobbal commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/ProtocolTests.kt
> +        }
That's pretty ugly indentation

2024-04-02 22:53 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/ProtocolTests.kt
> +        }
right you are, I will fix it!

2024-04-02 23:25 UTC, merged