Protocol support for C# (including Async) with tests!
cricut/FishyJoes pull request #206
Opened 2024-04-11 17:28 UTC by dvosscricut

Protocol support for C# (including Async) with tests!

2024-04-11 20:46 UTC, cobbal requested changes
Nice to see the iota stuff largely unchanged

2024-04-11 20:46 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +    var implements: [Type] { get }
I'm assuming this is SourceryRuntime.Type, not Swift.Type. FishyJoes avoids using this type because it is very often missing (especially across modules) and other reasons that I forget. Instead, this should either be BetterType or TranslatedProtocol.

2024-04-11 20:46 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +        let (productFields, productMethods) = CSharpClass.separate(fieldsAndMethods: fieldsAndMethods)
This is not an improvement. It's just more code that previously was centralized.

2024-04-11 20:46 UTC, cobbal commented on Sources/FishyJoesCore/Translators/CSharpTranslator.swift
> +        var implementsProtocol = false
should "implementsProtocol" be "isOverride"?

2024-04-11 20:46 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/CSharpClass.swift
> +    let isExternalWitness: Bool
This should not be part of CSharpClass. Thankfully, it doesn't seem to be used at all and I think it can be safely deleted.

2024-04-11 20:46 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/CSharpProtocolClass.swift
> +                fragment.output("public \(field.type.name) \(CSharpClass.deforbidify(field.name)) { get; \(field.isPubliclyWritable ? "set;" : "") }")
In C# we use getter methods for all computed properties because (among other reasons) it can cause infinite loops in the debugger, as it recursively eagerly evaluates all fields. https://github.com/cricut/FishyJoes/blob/main/Sources/FishyJoesCore/Translators/CSharpTranslator.swift#L150 . We should probably export all protocol variables as methods to avoid similar traps. As a bonus, it nicely sidesteps the "spit out an empty setter, because C# compels us" issue

2024-04-11 20:46 UTC, cobbal commented on c-sharp-runtime/src/Utilities.cs
> +                System.Diagnostics.Debug.WriteLine($"=== Begin live GC handles {TrackedHandlesClone.Count} ===");
I don't think duplicate logging should be committed. It should probably be just using Console.WriteLine, and if the behavior of that needs to be changed it can be. I sent you an example in teams.

2024-04-11 21:06 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +    var implements: [Type] { get }
Yes, it's an array of SourceryRuntime.Type, in fact SourceryProtocol. The reason I need it is I need the actual field names that are declared by the SourceryProtocol in order to determine whether or not to ignore the asMethod way of declaring properties or not. These are not included in BetterType, though I believe they are in TranslatedProtocol, so I could use that.

In a C# Interface, I declare properties as the property name with a getter and setter, and the setter is empty if the property is read only.  Then, anything that implements that interface needs to use the same naming.

This is opposed to declaring a separate GetSomeField and SetSomeField methods for properties, as is GetSomeField is currently declared for get only properties. 

I didn't want to mess with any existing generated names, just future ones so I needed this check (done in CSharpTranslator around line 135.

2024-04-11 21:17 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +        let (productFields, productMethods) = CSharpClass.separate(fieldsAndMethods: fieldsAndMethods)
The field/method separation code, previously duplicated in CSharpProductClass and CSharpEnumClass, was once again duplicated in the new CSharpProtocolClass.

It's better to put common code in a common place, such as a method. Additionally, the initializer override in CSharpProtocolClass can be entirely done away with, making the code smaller and cleaner. (Also, Sonar cloud dislikes duplicated code).

And fields, methods, and conformances became common fields on CSharpClass.

It's the same modification that was done for previously done for Dart and passed off.

2024-04-11 21:20 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/CSharpClass.swift
> +    let isExternalWitness: Bool
isExternalWitness is used in DartProductClass to know whether or not to generate ffi for storedFields.

ha ha! button used in C#. So yes indeed it can and will be deleted. Like a Cyberman deleting obsolete units.

2024-04-11 21:23 UTC, dvosscricut commented on c-sharp-runtime/src/Utilities.cs
> +                System.Diagnostics.Debug.WriteLine($"=== Begin live GC handles {TrackedHandlesClone.Count} ===");
<high pitched lemming voice when you click on start level in lemmings 2 tribes> "ok!"

2024-04-11 21:25 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/CSharpProtocolClass.swift
> +                fragment.output("public \(field.type.name) \(CSharpClass.deforbidify(field.name)) { get; \(field.isPubliclyWritable ? "set;" : "") }")
well, I wondered why that was that way. Ok then, that could simplify some previous code issues.

I suppose if it's a property with a setter then we use a normal property, right?

2024-04-11 21:29 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/CSharpProtocolClass.swift
> +                fragment.output("public \(field.type.name) \(CSharpClass.deforbidify(field.name)) { get; \(field.isPubliclyWritable ? "set;" : "") }")
ah but protocol properties have no setters because there's no set throws in swift, only get throws. womp womp.

2024-04-11 23:12 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +    var implements: [Type] { get }
well, now that all properties on protocols are exported as methods for C#, perhaps I don't need this anymore.

2024-04-11 23:14 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/CSharpTranslator.swift
> +        var implementsProtocol = false
not in this case, as exported properties of an object conforming to a protocol do not require the override notation. But, since our recent discussion about exporting all properties on a protocol as methods, perhaps this no longer matters so much.

2024-04-11 23:16 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/CSharpTranslator.swift
> +        var implementsProtocol = false
actually, I think I still need it, in order to know if I need to generate the GetSomeProperty on an object conforming to a protocol/interface in C# or not.

2024-04-12 21:44 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/CSharpTranslator.swift
> +        var implementsProtocol = false
nope, turns out I don't need it. ha ha!

2024-04-12 21:48 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +    var implements: [Type] { get }
indeed, I don't! And, I have remooved them

2024-04-12 21:53 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/CSharpProtocolClass.swift
> +                fragment.output("public \(field.type.name) \(CSharpClass.deforbidify(field.name)) { get; \(field.isPubliclyWritable ? "set;" : "") }")
experiments yesterday showed that no more debugger crash with dotnet 8, however there is a crash with toString.

The GetSomeField() requirement is a pain for structs implementing protocols/interfaces but I have done it according to your wishes. Technically, C# tradition does dictate for computed e.g. get only properties to use a method with a Get prefix instead. I have made the code generator generate such a method that returns the stored property in the case of a struct implementing a protocol field requirement as a read/write property.

2024-04-16 15:34 UTC, cobbal requested changes

2024-04-16 15:34 UTC, cobbal commented on integration-tests/TestAPI-bindings/c-sharp/Cricut.TestAPI/generated/Collections.cs
> +            public System.Collections.Generic.IList<bool> GetBoolArray() {
Was this intended to be added? I didn't think this type conformed to any protocols

2024-04-16 15:53 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/c-sharp/Cricut.TestAPI/generated/Collections.cs
> +            public System.Collections.Generic.IList<bool> GetBoolArray() {
hmmm... GetSomeProperty should be added for objects conforming to protocols, but no need to add if they don't. I'll have to fix that one, good catch.

2024-04-16 16:27 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/c-sharp/Cricut.TestAPI/generated/Collections.cs
> +            public System.Collections.Generic.IList<bool> GetBoolArray() {
fixed!

2024-04-16 19:28 UTC, cobbal approved these changes
Code is a little complex, but looks good otherwise

2024-04-16 19:28 UTC, cobbal commented on Sources/FishyJoesCore/Translators/CSharpTranslator.swift
> +    isInProtocolCheck:
I don't think this label is necessary

2024-04-16 19:28 UTC, cobbal commented on Sources/FishyJoesCore/Translators/CSharpTranslator.swift
> +           !implements.isEmpty {
This condition isn't needed

2024-04-16 19:51 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/CSharpTranslator.swift
> +    isInProtocolCheck:
good point

2024-04-16 19:51 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/CSharpTranslator.swift
> +           !implements.isEmpty {
good point

2024-04-16 20:13 UTC, merged