Protocol Support for Node
cricut/FishyJoes pull request #213
Opened 2024-05-03 22:33 UTC by dvosscricut

Protocol Support for Node

2024-05-06 17:13 UTC, kellyo-cricut commented on integration-tests/TestAPI-bindings/node-test/Protocols.test.ts
> +    TestAPI.TestProtocolEnum.foo("qux");
What are these calls on 89/91 checking?

2024-05-06 17:13 UTC, kellyo-cricut commented on integration-tests/TestAPI-bindings/node-test/Protocols.test.ts
Nit- almost all of the `let` in here could be `const`

2024-05-06 18:30 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/node-test/Protocols.test.ts
> +    TestAPI.TestProtocolEnum.foo("qux");
these are functions that return void, but you can see them printing out stuff on the console. They just have a print statement in the body.

2024-05-07 21:23 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/node-test/Protocols.test.ts
@kellyo-cricut nit has been fixed

2024-05-07 21:44 UTC, cobbal requested changes
Looking pretty good. Structure looks solid at this point.

2024-05-07 21:44 UTC, cobbal commented on Sources/FishyJoesCore/FishyJoesContext.swift
> +            let methods = methods.compactMap { Method($0, type: type, protocolName: protocolName) }
This new parameter comes directly from type, but type is already being passed in. Could save some complexity by not passing it.

2024-05-07 21:44 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        fragment.output("let env = _nodeWitness.env")
This isn't safe in the presence of threads (env is only valid for 1 thread). Instead the same machinery that function types use should be used.

2024-05-07 21:44 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        fragment.output("let env = _nodeWitness.env")
Looks like that's "syncOnMainThread": https://github.com/cricut/FishyJoes/blob/main/Sources/FishyJoesNodeRuntime/NodeFunction.swift#L108

2024-05-07 21:44 UTC, cobbal commented on Sources/FishyJoesNodeRuntime/NodeReference.swift
> +    public var ref: NAPI.Ref
`env` should not be added for reasons above. `ref` shouldn't need to be public, this class should hide that detail.

2024-05-07 21:44 UTC, cobbal commented on Tests/NAPITests/node-tests/runner.js
> +  const { NAPI } = await import("../../../Sources/FishyJoesNodeRuntime/Templates/wasm-napi.js");
I think this change broke the integration tests. Possibly you were running the tests from an unexpected working directory.

2024-05-07 21:44 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        fragment.output("let \(field.name) = try env.getNamedProperty(napiValue, \"\(field.name)\")")
The second "field.name" isn't right if this has been renamed on export

2024-05-07 21:44 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        if case let .function(params, resVal, _, _) = field.type {
This is very odd. Types shouldn't need to be special cased here.

2024-05-07 21:44 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                fragment.outputBlock("let fromCoreClass = try NodeClass(") {
This doesn't really need to be a full class. A function inside an object would be more idiomatic

2024-05-07 21:44 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                                    if !defaultMethods.isEmpty {
unneeded if statement. Embrace zero as a useful number.

2024-05-07 21:44 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                                    fragment.output("let createdCore = try env.callFunction(global, create, [coreArg])")
createdCore is perhaps a bad name for this, since it's the full protocol object, created from the core. Maybe "result" would be a better name?

2024-05-07 21:44 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                                    fragment.output("let createdCore = try env.callFunction(global, create, [coreArg])")
The first argument should probably be `object`, since that's what javascript would pass in when calling `Object.create(...)`

2024-05-07 21:44 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +        // Node objects needs default methods in order to conform to the interfaces it implements, though as an optional method that if the user does not implement, will use the defined default metho
I don't understand why "TranslatedReference" would need to chage to handle default methods, and the comment here doesn't really explain why references would implement protocols differently from all other types

2024-05-07 21:44 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +                defaultMethodsForNode.compactMap { context.ts(method: $0) }
This is really ugly indentation. Is this really what Xcode recommends?

2024-05-07 21:44 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/TypeScriptAnnotations.swift
> +//                                }
Commented code should be removed or explained.

2024-05-07 21:44 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/TypeScriptAnnotations.swift
> +                        if !interface.documentation.isEmpty {
unnecessary if

2024-05-07 21:44 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/TypeScriptAnnotations.swift
> +        func output(method: Method, inClass: Bool, optionalMethodsForDefaults: Bool = false, isCore: Bool = false) {
Feels like there are a lot more options expressible than combinations of options used. I'm not sure what the right combination is and whether it belongs in the TSType.Method class or as function arguments.

2024-05-07 21:44 UTC, cobbal commented on Sources/FishyJoesCore/Translators/NodeTranslator.swift
> +    func output(method: Method, explicitThis: Bool, context: FishyJoesContext, fragment: SourceFragment, newLineTerminated: Bool = true, converterName: String? = nil) {
I'm seeing a lot of the defaulted stuff on methods in this PR, but not much on properties. There may also be TS limitations for those: https://github.com/microsoft/TypeScript/issues/36883

2024-05-07 21:44 UTC, cobbal commented on integration-tests/TestAPI-bindings/Sources/Generated/NodeInterface/TestAPI.AProtocol+node.swift
> +            throw error
Is this necessary?

2024-05-07 21:44 UTC, cobbal commented on integration-tests/TestAPI-bindings/c-sharp/Cricut.TestAPI/generated/TestProtocolStruct.cs
> +        public bool Bar(
Did the order here become non-deterministic (bad) or is this a one-time change (fine)?

2024-05-07 22:01 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/node-test/Protocols.test.ts
> +    TestAPI.TestProtocolEnum.foo("qux");
If I knew how to test verify what's going to stdout on the console, then I could verify them. Otherwise, I just manually verify them by looking at the console and checking that it prints out as it ought.

2024-05-07 22:07 UTC, dvosscricut commented on Sources/FishyJoesCore/FishyJoesContext.swift
> +            let methods = methods.compactMap { Method($0, type: type, protocolName: protocolName) }
good point, fixed now

2024-05-07 22:15 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        fragment.output("let env = _nodeWitness.env")
ok, fixed now

2024-05-07 22:16 UTC, dvosscricut commented on Tests/NAPITests/node-tests/runner.js
> +  const { NAPI } = await import("../../../Sources/FishyJoesNodeRuntime/Templates/wasm-napi.js");
ok, I put it back.

2024-05-07 22:19 UTC, dvosscricut commented on Sources/FishyJoesNodeRuntime/NodeReference.swift
> +    public var ref: NAPI.Ref
ok, fixed now

2024-05-07 22:21 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        fragment.output("let \(field.name) = try env.getNamedProperty(napiValue, \"\(field.name)\")")
ok

2024-05-07 22:23 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        if case let .function(params, resVal, _, _) = field.type {
what about the case of a field exported as a method? Would I not need to check for that here?

2024-05-07 22:25 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                                    if !defaultMethods.isEmpty {
good point

2024-05-07 22:28 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                                    fragment.output("let createdCore = try env.callFunction(global, create, [coreArg])")
renamed createdCore to result

2024-05-07 22:29 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                                    fragment.output("let createdCore = try env.callFunction(global, create, [coreArg])")
made first arg object instead of global

2024-05-07 22:30 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +                defaultMethodsForNode.compactMap { context.ts(method: $0) }
indeed this is the result of CTRL+I

2024-05-07 22:31 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/TypeScriptAnnotations.swift
> +//                                }
cruft uncruftified sir

2024-05-07 22:32 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/TypeScriptAnnotations.swift
> +                        if !interface.documentation.isEmpty {
ok

2024-05-07 22:37 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/NodeTranslator.swift
> +    func output(method: Method, explicitThis: Bool, context: FishyJoesContext, fragment: SourceFragment, newLineTerminated: Bool = true, converterName: String? = nil) {
There aren't default implementations on Swift protocols for properties though, just for methods.

2024-05-07 22:38 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/Sources/Generated/NodeInterface/TestAPI.AProtocol+node.swift
> +            throw error
no, it's just a leftover from debugging. fixed now

2024-05-07 22:38 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/c-sharp/Cricut.TestAPI/generated/TestProtocolStruct.cs
> +        public bool Bar(
it's a one time thing. You can check this by running fishy joes multiple times and observing no file changes.

2024-05-07 23:50 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        if case let .function(params, resVal, _, _) = field.type {
for example, const42, add3Things, fifthThing etc. on TestAsyncFunctions?

These are fields/properties/variables that contain closures.

It just so happens that if I just use the field it generates an AsyncFunctionXConverter<...>.fromNode that works in tests, so I can get rid of it, but I didn't know that I could!

2024-05-08 01:05 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                fragment.outputBlock("let fromCoreClass = try NodeClass(") {
ok, I did it create an object with a function on it way now

2024-05-08 01:06 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/NodeTranslator.swift
> +    func output(method: Method, explicitThis: Bool, context: FishyJoesContext, fragment: SourceFragment, newLineTerminated: Bool = true, converterName: String? = nil) {
I needed the special stuff for handling the default implementations of methods, so that's why the special stuff isn't on properties.

2024-05-08 01:10 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/TypeScriptAnnotations.swift
> +        func output(method: Method, inClass: Bool, optionalMethodsForDefaults: Bool = false, isCore: Bool = false) {
optionalMethodsForDefaults and isCore are options only used for default implementations of functions for generating the typescript interfaces for them. If you disable them (set them to false, you just get the function definitions you had before

basically it's should we put a question mark after the method name, or not.
And should we output an extra "this: " first argument for the method, or not.

It seems to me it belongs in this functions args, not the Method struct itself, because only Node needs it. The other languages don't.

2024-05-08 01:18 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +        // Node objects needs default methods in order to conform to the interfaces it implements, though as an optional method that if the user does not implement, will use the defined default metho
TranslatedReference implements node default methods similarly to TranslatedStruct. Perhaps TranslatedEnum should as well? But the rest of the TranslatedTypes (well, besides TranslatedProtocol of course) don't.

2024-05-08 16:44 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        if case let .function(params, resVal, _, _) = field.type {
so, I got rid of the function case for you. Now all fields are handled the same

2024-05-08 18:11 UTC, cobbal commented on Sources/FishyJoesCore/Translators/NodeTranslator.swift
> +    func output(method: Method, explicitThis: Bool, context: FishyJoesContext, fragment: SourceFragment, newLineTerminated: Bool = true, converterName: String? = nil) {
> There aren't default implementations on Swift protocols for properties though, just for methods.

Where does this restriction come from? Swift allows defaulted properties just fine.

2024-05-08 18:12 UTC, cobbal commented on integration-tests/TestAPI-bindings/node-test/Protocols.test.ts
> +    TestAPI.TestProtocolEnum.foo("qux");
These should be fixed at some point. A test suite that relies on looking at the console is not a very good test suite.

2024-05-08 18:15 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        fragment.output("let \(field.name) = try env.getNamedProperty(napiValue, \"\(field.name)\")")
This should also be in the test suite

2024-05-08 18:26 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                fragment.outputBlock("let coreObject = try env.createFunction(") {
This doesn't need to be a function at all. Just use `env.createObject`

2024-05-08 20:05 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +        // Node objects needs default methods in order to conform to the interfaces it implements, though as an optional method that if the user does not implement, will use the defined default metho
How does a struct have default methods either? This just doesn't make any sense.

2024-05-08 20:10 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/TypeScriptAnnotations.swift
> +        func output(method: Method, inClass: Bool, optionalMethodsForDefaults: Bool = false, isCore: Bool = false) {
I was referring to `TSType.Method` specifically, not to the other `Method` type(s)

2024-05-08 20:37 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/NodeTranslator.swift
> +    func output(method: Method, explicitThis: Bool, context: FishyJoesContext, fragment: SourceFragment, newLineTerminated: Bool = true, converterName: String? = nil) {
Swift allows default values for computed properties, but not stored properties. I suppose we could add support for default computed properties in Swift protocols, but I think that should be on a separate PR/PBI, because none of the other languages we've done for Protocol Support support default computed properties either.
![Screenshot 2024-05-08 at 2 35 47 PM](https://github.com/cricut/FishyJoes/assets/48807612/143bad49-4589-4678-ac3c-bf5aa16762d7)

2024-05-08 20:39 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/node-test/Protocols.test.ts
> +    TestAPI.TestProtocolEnum.foo("qux");
well, perhaps, but how about on a separate PR/PBI? Because none of the other languages that have Protocol support have verified the console output/functions that return void either.

2024-05-08 21:30 UTC, cobbal commented on Sources/FishyJoesCore/Translators/NodeTranslator.swift
> +    func output(method: Method, explicitThis: Bool, context: FishyJoesContext, fragment: SourceFragment, newLineTerminated: Bool = true, converterName: String? = nil) {
Sounds like a bug in the implementation for other languages

2024-05-08 22:04 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                        fragment.output("let \(field.name) = try env.getNamedProperty(napiValue, \"\(field.name)\")")
good catch! I had to fix it for kotlin, dart, and c# also (done on this PR!

2024-05-08 22:09 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/TypeScriptAnnotations.swift
> +        func output(method: Method, inClass: Bool, optionalMethodsForDefaults: Bool = false, isCore: Bool = false) {
I'm not sure what you mean. There's a type: TSType on the Parameters of a method, but there's no TSType.method, just named, optional, union, exactString, and promise.

However, the function args do work.

If you decide what you'd like better later we could always change it.

Since it's currently undecided, could the function args pass for now?

2024-05-08 22:11 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/NodeTranslator.swift
> +    func output(method: Method, explicitThis: Bool, context: FishyJoesContext, fragment: SourceFragment, newLineTerminated: Bool = true, converterName: String? = nil) {
indeed it could be a missing feature for full simple protocol support.

But, may I please do it on a separate PBI ticket and PR (since it needs to be done for all exported languages)?

2024-05-08 22:15 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                fragment.outputBlock("let coreObject = try env.createFunction(") {
good point

2024-05-08 22:19 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/node-test/Protocols.test.ts
> +    TestAPI.TestProtocolEnum.foo("qux");
I made a PBI ticket for it here: https://cricut.visualstudio.com/Cricut/_workitems/edit/476434

2024-05-08 22:20 UTC, dvosscricut commented on Sources/FishyJoesCore/Translators/NodeTranslator.swift
> +    func output(method: Method, explicitThis: Bool, context: FishyJoesContext, fragment: SourceFragment, newLineTerminated: Bool = true, converterName: String? = nil) {
I made a ticket for it here: https://cricut.visualstudio.com/Cricut/_workitems/edit/476436

2024-05-08 22:48 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/TypeScriptAnnotations.swift
> +        func output(method: Method, inClass: Bool, optionalMethodsForDefaults: Bool = false, isCore: Bool = false) {
I apologize, I was misremembering the organization. I meant `TypeScriptAnnotations.Method`, which is TS-specific

2024-05-08 22:58 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +        // Node objects needs default methods in order to conform to the interfaces it implements, though as an optional method that if the user does not implement, will use the defined default metho
The TranslatedReference/Struct 'defaultMethodsForNode' is for the Type.d.ts definitions.

It's how we did it for default implementations in type script to work for users conforming to AProtocolCore

```
interface AProtocol {
  hasADefaultImpl(...
}

interface AProtocolCore {
  hasADefaultImpl?(...
}
namespace AProtocol {
  function fromCore(core: AProtocolCore): AProtocol
}

// generated class conforming to interface
export class AProtocolImpl implements AProtocol {
  hasADefaultImplementation(...
}

// user defined class conforming to interface
class TestCoreClass implements TestAPI.AProtocolCore {
  // don't need to define default method here since for AProtocolCore the method is optional
}

// to actually use the class need to run it through .fromCore function:
const testCoreClass = new TestCoreClass("Gitang", false);
 const testClass = TestAPI.AProtocol.fromCore(testCoreClass);
```

now can call `testClass.hasADefaultImpl(...` and have it work.

Now for generated classes I could have them conform to AProtocolCore instead of AProtocol, and then I wouldn't need to put the hadADefaultImpl functions in their definition in Type.d.ts, but then users would have to run them through the AProtocol.fromCore method to actually use them. Is that what we really want?

Or perhaps we'd want some custom constructor function on the generated classes conforming to the protocol, that automatically returns the AProtocol.fromCore conforming to AProtocol instead of just itself conforming to AProtocolCore?

2024-05-08 23:01 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +        // Node objects needs default methods in order to conform to the interfaces it implements, though as an optional method that if the user does not implement, will use the defined default metho
perhaps I should name them "defaultMethodsForNodeTypeDefinition" instead?

I don't have access to the type.implements  later in the code so that's why I got them here and stored them in a property.

2024-05-08 23:18 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +        // Node objects needs default methods in order to conform to the interfaces it implements, though as an optional method that if the user does not implement, will use the defined default metho
would you prefer something more like this in the Type.d.ts?

```
class AProtocolImplementation implements AProtocolCore {
        constructor(foo: string, baz: boolean)
        foo: string;
        baz: boolean;

        withDefaultMethods(): AProtocol
        /**
         * <!-- FishyJoes.export(bar) -->
         */
        bar(
            x: number,
            y: number
        ): TestAPI.AProtocol;
    }
```

Then to use the generated class you'd need to do 

```
let a = AProtocolImplementationCore("Foo!", false).withDefaultMethods()
a.hasADefaultImplemention(...
```

would that be better?

2024-05-09 20:26 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/node-test/Protocols.test.ts
> +    TestAPI.TestProtocolEnum.foo("qux");
Due to Andrew's decision that testing stdout output is undesirable, and the difficulty in doing so

I will remove the print to stdout part of the methods that do so by wrapping it in a static property definition so that I can still see them if I want but other people won't have to.

The test for a method that returns void will now just be that the method is called and no crashes happen such as would happen if the method did not exist or if there was a name mismatch.

Additionally, I could add tests that have an inout arg and/or callback as an arg to methods.

2024-05-09 20:56 UTC, dvosscricut commented on integration-tests/TestAPI-bindings/node-test/Protocols.test.ts
> +    TestAPI.TestProtocolEnum.foo("qux");
I have minimized stdout to just the pid printout (useful for attaching to in Xcode for node/Swift dual debugging), with the rest of the prints to stdouts being behind a constant variable check.

2024-05-09 20:58 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +        // Node objects needs default methods in order to conform to the interfaces it implements, though as an optional method that if the user does not implement, will use the defined default metho
glad we had that chat.

agreed, methods should just carry default methods with no duplicates in case generated struct/reference implemented a default method on the swift side. I should add a test case to test for this.

The only thing that needs to know if a method is default or not is TranslatedProtocol.

agreed, logic to get the no duplicate list of methods from input methods and protocol default implementation methods should be a common logic function.

2024-05-14 00:24 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/TypeScriptAnnotations.swift
> +        func output(method: Method, inClass: Bool, optionalMethodsForDefaults: Bool = false, isCore: Bool = false) {
oh ok. apology accepted. so optionalMethodsForDefaults is per interface, not per method, so I'd vote for it to remain a function argument.

similarly, the isCore pertains to the interface, not the method itself per se. So remaining function arguments it is!

2024-05-14 00:24 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +        // Node objects needs default methods in order to conform to the interfaces it implements, though as an optional method that if the user does not implement, will use the defined default metho
ok I have implemented this as we discussed.

2024-05-14 20:29 UTC, cobbal requested changes
Things are looking good. 1 issue, 1 question

2024-05-14 20:29 UTC, cobbal commented on Sources/FishyJoesCore/Method.swift
> +        let methods = Method.methodsPreferring(.defaultImplementation, methods: normalMethods + defaultMethods)
Why does this prefer the default implementation? Shouldn't the overriden implementation be preferred in most contexts?

2024-05-14 20:29 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +    static func methodsPreferring(_ preference: MethodTypePreference, methods: [SourceryMethod]) -> [SourceryMethod] {
Do we really need both this and the one in Method?

2024-05-14 21:04 UTC, dvosscricut commented on Sources/FishyJoesCore/Method.swift
> +        let methods = Method.methodsPreferring(.defaultImplementation, methods: normalMethods + defaultMethods)
good catch! you are right, for this method (used for everything but Protocols), the normal method should override the default method.

It turns out to not make in any difference in the code generation, but in principle it makes a difference to make sense rather than nonsense. fixed.

2024-05-14 21:44 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +    static func methodsPreferring(_ preference: MethodTypePreference, methods: [SourceryMethod]) -> [SourceryMethod] {
In Theory, no. I'm having a dilly of a time just trying to get it to work using just one of them though.

2024-05-15 15:55 UTC, cobbal approved these changes

2024-05-15 16:00 UTC, merged