Add Default Computed Properties support to exported Protocols
cricut/FishyJoes pull request #218
Opened 2024-05-23 21:44 UTC by dvosscricut

Add Default Computed Properties support to exported Protocols

https://cricut.visualstudio.com/Cricut/_workitems/edit/476436

2024-05-28 19:53 UTC, cobbal requested changes
I got part way through reviewing this, and was trying to test some changes, but the big question I just can't get past is why are default variables treated so differently from default methods? Is there a technical reason? I know you said something about definedInType, but I think that may be a symptom, not a cause.

The difference either needs to go away, or it needs to become obvious why it's there. Then it will be easier to review this without starting from scratch.

2024-05-28 19:53 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +
This is a lot of duplicated code. The sans-method-struct and the sans-field-struct should be almost the same

2024-05-28 19:53 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                    kotlinVariable.body = "\tget() = __jni__default_\(defaultMethodForVariable.name)(this)"
Tabs should not be used, especially when mixed with spaces

2024-05-28 19:53 UTC, cobbal commented on Sources/FishyJoesCore/Field.swift
> +    init?(_ variable: SourceryVariable, type: Type?, isDefaultImplementation: Bool) {
What are the reasons for the differences between this and Method?

2024-05-28 19:53 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +                        hasProperties ||= context.nodeTranslator.outputProperties(computedVariables: defaultProperties, context: context, fragment: fragment, converterName: converterType.name)
splitting things out only to immediately recombine them

2024-05-28 19:53 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +            fatalError("☠️ Error on \(sourceType.name): Exported structs must have at least one stored property, it's the law 👮!")
This is probably too strict of a restriction to place on structs. A struct without any members is perfectly valid, and we should be able to export it.

2024-05-28 20:15 UTC, dvosscricut commented
> I got part way through reviewing this, and was trying to test some changes, but the big question I just can't get past is why are default variables treated so differently from default methods? Is there a technical reason? I know you said something about definedInType, but I think that may be a symptom, not a cause.
> 
> The difference either needs to go away, or it needs to become obvious why it's there. Then it will be easier to review this without starting from scratch.

definedInType for default implementations of computed variables can be SourceryRuntime.Type instead of SourceryProtocol.

That's the reason for the difference.

I don't know if methods have the same problem, but I should check.

2024-05-29 00:45 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +
Code duplication indeed! I have combined them now!

2024-05-29 00:48 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                    kotlinVariable.body = "\tget() = __jni__default_\(defaultMethodForVariable.name)(this)"
spaces it is! 
![space_sloth](https://github.com/cricut/FishyJoes/assets/48807612/6e54a526-9c1c-494f-9843-bfb19642ed53)

2024-05-29 00:49 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +            fatalError("☠️ Error on \(sourceType.name): Exported structs must have at least one stored property, it's the law 👮!")
A data class in Kotlin (which is what KotlinProductClass exports to) without any members is invalid:

https://kotlinlang.org/docs/data-classes.html
* The primary constructor must have at least one parameter.

2024-05-29 00:55 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +                        hasProperties ||= context.nodeTranslator.outputProperties(computedVariables: defaultProperties, context: context, fragment: fragment, converterName: converterType.name)
good point. I think at one point they were different but then I fixed it but never recombined them.

2024-05-29 00:58 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +                        hasProperties ||= context.nodeTranslator.outputProperties(computedVariables: defaultProperties, context: context, fragment: fragment, converterName: converterType.name)
fixed now

2024-05-29 01:01 UTC, dvosscricut commented on Sources/FishyJoesCore/Field.swift
> +    init?(_ variable: SourceryVariable, type: Type?, isDefaultImplementation: Bool) {
It's needed due to definedInType for default implementations of computed variables can be SourceryRuntime.Type instead of SourceryProtocol. Which makes me have to pass in isDefaultImplementation explicitly instead of being able to use variable.definedInType is SourceryProtocol.

I'll check if methods have a similar problem, they may need the same treatment.

2024-05-29 02:37 UTC, dvosscricut commented on Sources/FishyJoesCore/Field.swift
> +    init?(_ variable: SourceryVariable, type: Type?, isDefaultImplementation: Bool) {
methods have a similar problem of a default method definedInType not being a SourceryProtocol but instead being a SourceryRuntime.Type instead. I checked this out with a breakpoint on line 171 of Method.swift, and doing a `po prot.defaultMethods()[0].definedInType is SourceryProtocol` and it came up false.

It's a good point worthy of investigation. Why aren't they the same? Could they be handled the same?

2024-05-29 02:46 UTC, dvosscricut commented on Sources/FishyJoesCore/Field.swift
> +    init?(_ variable: SourceryVariable, type: Type?, isDefaultImplementation: Bool) {
so it looks like this logic here in methodsPreferring would fail for methods that are not SourceryProtocol but ought to be `let isMostlyEqualMethodADefaultImplementation = mostlyEqualMethod.isExtension && (mostlyEqualMethod.definedInType is SourceryProtocol)`

So I should convert over the methods stuff to do it similarly to how the variables do it, with the isDefinedInProtocol property on the wrapper SourceryVariablePlus struct. And, I will!

2024-05-29 03:13 UTC, dvosscricut commented on Sources/FishyJoesCore/Field.swift
> +    init?(_ variable: SourceryVariable, type: Type?, isDefaultImplementation: Bool) {
Ok, I've converted over SourceryMethod to handle methods like variables from Sourcery

Because method.definedInType is SourceryProtocol can be false even when it should be true, therefore we must keep track of isDefinedInProtocol instead to give us the that information that we need to compute isDefaultImplementation.

2024-05-29 03:18 UTC, dvosscricut commented
> > I got part way through reviewing this, and was trying to test some changes, but the big question I just can't get past is why are default variables treated so differently from default methods? Is there a technical reason? I know you said something about definedInType, but I think that may be a symptom, not a cause.
> > The difference either needs to go away, or it needs to become obvious why it's there. Then it will be easier to review this without starting from scratch.
> 
> definedInType for default implementations of computed variables can be SourceryRuntime.Type instead of SourceryProtocol.
> 
> That's the reason for the difference.
> 
> I don't know if methods have the same problem, but I should check.

@cobbal okay I checked and methods have the same problem, and I just did them the same as variables for the same solution.

2024-05-30 00:30 UTC, dvosscricut commented on Sources/FishyJoesCore/Field.swift
> +    init?(_ variable: SourceryVariable, type: Type?, isDefaultImplementation: Bool) {
OK, now I've gotten rid of SourceryMethodPlus and SourceryVariablePlus and just use Method.methods(type:) and Field.fields(type:). hooray!

2024-05-30 19:48 UTC, cobbal approved these changes
This is looking really good. Diff made a lot more sense to me this time around. One minor cleanup could still be done.

2024-05-30 19:48 UTC, cobbal commented on Sources/FishyJoesCore/Field.swift
> +        self.isDefaultImplementation = isDefaultImplementation
This change can probably be reverted now.

2024-05-30 19:48 UTC, cobbal commented on Sources/FishyJoesCore/Field.swift
> +        self.isDefaultImplementation = isDefaultImplementation
Sanity check, I dropped a `precondition(isDefaultImplementation == (type is SourceryProtocol && variable.definedInType?.isExtension == true))` and everything still worked. It should be safe to delete the `isDefaultImplementation` parameter to centralize the logic to this method.

2024-05-30 19:48 UTC, cobbal commented on Sources/FishyJoesCore/Method.swift
> +    init?(_ method: SourceryMethod, type: Type?, isDefaultImplementation: Bool, protocolName: String?) {
This parameter too

2024-05-30 20:19 UTC, dvosscricut commented on Sources/FishyJoesCore/Field.swift
> +        self.isDefaultImplementation = isDefaultImplementation
ok

2024-05-30 20:19 UTC, dvosscricut commented on Sources/FishyJoesCore/Method.swift
> +    init?(_ method: SourceryMethod, type: Type?, isDefaultImplementation: Bool, protocolName: String?) {
<jimmy McLemming> "Okay!"

2024-05-30 20:45 UTC, merged