AB#478509 Use BetterType instead of String for Conformances so we have a namespace for conformances
cricut/FishyJoes pull request #220
Opened 2024-05-29 15:55 UTC by dvosscricut

AB#478509 Use BetterType instead of String for Conformances so we have a namespace for conformances

2024-05-29 17:29 UTC, cobbal requested changes
Nice. That worked out well. There are just a couple places where a swift type is placed into a context that should have a different-lannguage type.

2024-05-29 17:29 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                conformances: [BetterType.named(.init(name: "SwiftReference(_swiftReference)", module: "fishyjoes.runtime"))]
This is the name of a kotlin class, It should be either a `KType` or a string, BetterType refers to swift types. (Maybe it should be called SwiftType... I'll have to think about that)

2024-05-29 17:29 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/CSharpClass.swift
> +    let conformances: Set<BetterType>
Same here

2024-05-30 16:27 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedProtocol.swift
> +                conformances: [BetterType.named(.init(name: "SwiftReference(_swiftReference)", module: "fishyjoes.runtime"))]
updated to use KotlinClass.KType inside The Kotlin Kingdom

We still use BetterType/SType when dwelling within the borders of the Swift Sovereign State.

2024-05-30 16:45 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/CSharpClass.swift
> +    let conformances: Set<BetterType>
CSharpClass.CSType is now used within the C# Kingdom

2024-05-30 16:52 UTC, cobbal requested changes

2024-05-30 16:52 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedEnum+cSharp.swift
> +            CSharpClass.CSType.named(package: $0.module, name: $0.nonNamespacedName)
This should be resolved and the csharptype pulled from the translatedtype. The swift type may not be named the same thing.

2024-05-30 17:20 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedEnum+cSharp.swift
> +            CSharpClass.CSType.named(package: $0.module, name: $0.nonNamespacedName)
ok! <high pitched lemming voice>

2024-05-30 19:50 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedEnum+cSharp.swift
> +            return CSharpClass.CSType.named(package: resolved.sourceType.module, name: resolved.sourceType.nonNamespacedName)
Use this: https://github.com/cricut/FishyJoes/blob/main/Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift#L11

2024-05-30 23:00 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedEnum+cSharp.swift
> +            return CSharpClass.CSType.named(package: resolved.sourceType.module, name: resolved.sourceType.nonNamespacedName)
ok, I did it for kotlinType as well

2024-05-31 21:36 UTC, cobbal approved these changes
Looks very good

2024-06-01 00:36 UTC, merged