AB#478507 Add Tests and Support for EmptyEnum/Struct/Class
cricut/FishyJoes pull request #222
Opened 2024-06-04 16:58 UTC by dvosscricut

Add Tests and Support for EmptyEnum/Struct/Class

EmptyEnum worked fine already but Struct and Class needed equals/hashCode and toString methods added since they can no longer be auto handled by Kotlin data class since that requires at least one stored parameter so we must go with a general Kotlin class which does not have those methods autohandled so we must implement them ourselves.

https://cricut.visualstudio.com/Cricut/_workitems/edit/478507

2024-06-04 17:15 UTC, cobbal requested changes

2024-06-04 17:15 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/KotlinProductClass.swift
> +                fragment.outputBlock("override fun equals(other: Any?): kotlin.Boolean {") {
Unparse is the wrong place to do this. They should be created in TranslatedStruct for empty structs like they're created in TranslatedReference for equatable references.

2024-06-04 23:42 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/KotlinProductClass.swift
> +                fragment.outputBlock("override fun equals(other: Any?): kotlin.Boolean {") {
"ok!"

2024-06-05 16:35 UTC, cobbal requested changes

2024-06-05 16:35 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +        }
Why did TranslatedReference need to change? Was there something wrong with the way it was already handling equatable?

2024-06-05 16:35 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +            let fieldsChecks = fields.map {
If there are no stored fields, this isn't necessary and probably shouldn't be done. Here's an example of a workaround for the restriction: https://discuss.kotlinlang.org/t/data-class-without-arguments-deprecated-in-1-0-why/60/15

2024-06-05 16:35 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/KotlinProductClass.swift
>                  classDeclaration = "class \(unqualifiedName) private constructor"
The constructor should be public for structs

2024-06-05 17:16 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedReference.swift
> +        }
because I didn't understand that swift class must conform to Hashable in order to get those __jni_swiftEquals type functions to autogenerate. But now, thanks to you, I know!

So, you're right TranslatedReference doesn't have to change!

2024-06-05 17:41 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedStruct.swift
> +            let fieldsChecks = fields.map {
ok

2024-06-05 17:41 UTC, dvosscricut commented on Sources/FishyJoesCore/Unparse/KotlinProductClass.swift
>                  classDeclaration = "class \(unqualifiedName) private constructor"
ok

2024-06-05 18:52 UTC, cobbal approved these changes

2024-06-05 19:16 UTC, merged