AB#492335 Filter conformances to FishyJoes exported ones
cricut/FishyJoes pull request #229
Opened 2024-06-11 22:16 UTC by dvosscricut

Filter conformances to FishyJoes exported ones

To fix CriGeo-bindings problem

It appears that Sourcery does not put in type.implements any protocols that are declared in the initial sttuct/class/enum declaration if they are not exported to FishyJoes, but it DOES put in type.implements any protocols that are declared in extensions to the struct/class/enum.

To deal with this, we must find first find all fishyjoes exported protocols, then filter type.implements by them in the translated struct/class/enum initializers when assigning to conformances.

https://cricut.visualstudio.com/Cricut/_workitems/edit/492335

2024-06-11 22:40 UTC, cobbal requested changes
I think this could be done more cleanly by adding a `func exportedConformances(in context: FishyJoesContext) -> [TranslatedProtocol]` to the TranslatedType extension.

Due to the nature of cycles, TranslatedTypes avoid needing to know about other TranslatedTypes while being initialized, and wait until the fragment generation stages to resolve the BetterTypes into TranslatedTypes.

Similarly, the decision about which protocols types should be exported should be delayed until conformances are used in the fragment generation. The suggested `exportedConformances` method should make this fairly low-repeated-code.

2024-06-12 20:26 UTC, cobbal requested changes

2024-06-12 20:26 UTC, cobbal commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +        return exportedConformances
This could be much simpler. The exportedProtocolSwiftTypes can be entirely deleted.
```suggestion
        conformances.compactMap { try? context.tryResolve(type: $0) as? TranslatedProtocol }
```

2024-06-12 20:30 UTC, dvosscricut commented
oops closed by accident

2024-06-12 20:39 UTC, cobbal approved these changes

2024-06-12 20:40 UTC, dvosscricut commented on Sources/FishyJoesCore/TranslatedTypes/TranslatedType.swift
> +        return exportedConformances
good point

2024-06-12 21:10 UTC, merged