fix: fix packing to handle xdls correctly
cricut/FishyJoes pull request #260
Opened 2024-10-18 20:40 UTC by dvosscricut

move tar of dart libs to pack from -bindings.yaml to pack command in CodeGen
Add xdls to dart cp commands in pack
remove dependency's xdls from c-sharp common lib directory before pack (keep direct xdls)

2024-10-21 16:17 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +        fishyJoesYamlConfigs.forEach { extraDynamicLibsToInstall.formUnion($0.extraDynamicLibraries) }
I worry that this will package the canvas model twice, once in the CriSVG-bindings release and once in the CriCanvas-bindings. It should only be included in the SVG package.

This might be pointing towards an inconsistency in how FishyJoes does dart packaging with how it does the rest of the languages.

2024-10-21 19:38 UTC, dvosscricut commented on Sources/FishyJoesExecute/CodeGen.swift
> +                    // Don't copy over any dependency's extraDynamicLibraries for Kotlin because it's bundled by maven from the dependency.
@cobbal  here is the change

2024-10-22 16:20 UTC, cobbal requested changes
Looks pretty good. Just 2 minor things

2024-10-22 16:20 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +                        find . -iname "*crisvg*"
This probably shouldn't be committed to this repo

2024-10-22 16:20 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +                            (path: "windows\(ps)native\(ps)\($0).dll", required: true)
These should not be marked as required, because they're platform specific. Linux likely won't have the windows library, etc.

2024-10-22 16:32 UTC, dvosscricut commented on Sources/FishyJoesExecute/CodeGen.swift
> +                        find . -iname "*crisvg*"
oh ha ha. good catch

2024-10-22 16:34 UTC, dvosscricut commented on Sources/FishyJoesExecute/CodeGen.swift
> +                            (path: "windows\(ps)native\(ps)\($0).dll", required: true)
ok

2024-10-22 16:48 UTC, cobbal approved these changes

2024-10-22 16:48 UTC, merged