Collection tests
cricut/FishyJoes pull request #27
Opened 2021-12-21 01:09 UTC by mstokercricut

* Tests similar to Primitives, but for Collections.
* Could use more tests related to mutability for collections...
* Also fixes a bug related to structs exported by reference that are marked Equatable, including tests

2022-01-04 22:27 UTC, cobbal requested changes
Good to see the TODOs. I'll take a look at them later.

2022-01-04 22:27 UTC, cobbal commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/CollectionTests.kt
> +        assertEquals(Collections.arrayOfInt, arrayListOf(2,7,3,5,8).map { it.toLong() })
use `1L` for long literals.

2022-01-04 22:27 UTC, cobbal commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/CollectionTests.kt
> +        assert(Collections.maybeSetOfInt?.containsAll(setOf(5,9,2,4,3).map { it.toLong() }) ?: false)
`assertEquals(thing, true)` is the preferred way to deal with `Bool?`

2022-01-04 22:27 UTC, cobbal commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/CollectionTests.kt
> +            null to 100,
Huh... didn't even know that was a thing in java.

2022-01-04 22:27 UTC, cobbal commented on integration-tests/TestAPI/Sources/TestAPI/Collections.swift
> +        public init(boolArray: [Bool] = [false,true], boolSet: Set<Bool> = [false,true], boolDictionary: [Bool : Bool] = [true:false, false:true], integerArray: [Int] = [2,7,3,5,8], integerSet: Set<I
Clearly I need to set up swiftlint for this project :D

2022-01-04 23:07 UTC, mstokercricut commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/CollectionTests.kt
> +        assertEquals(Collections.arrayOfInt, arrayListOf(2,7,3,5,8).map { it.toLong() })
Ah. Much better. I knew it couldn't be that hard.

2022-01-04 23:51 UTC, mstokercricut commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/CollectionTests.kt
> +            null to 100,
I was surprised too. I wrote the test, and it passed, so... I guess it is.

2022-01-04 23:51 UTC, mstokercricut commented on integration-tests/TestAPI-bindings/kotlin/src/test/kotlin/com/cricut/testapi/CollectionTests.kt
> +        assert(Collections.maybeSetOfInt?.containsAll(setOf(5,9,2,4,3).map { it.toLong() }) ?: false)
Much nicer.

2022-01-04 23:53 UTC, mstokercricut commented on integration-tests/TestAPI/Sources/TestAPI/Collections.swift
> +        public init(boolArray: [Bool] = [false,true], boolSet: Set<Bool> = [false,true], boolDictionary: [Bool : Bool] = [true:false, false:true], integerArray: [Int] = [2,7,3,5,8], integerSet: Set<I
As long as all the generated code passes too... 😎

2022-01-05 15:59 UTC, cobbal approved these changes

2022-01-05 18:52 UTC, merged