The Start of C Hashtag Support
cricut/FishyJoes pull request #35
Opened 2022-04-14 16:08 UTC by bscothern-Cricut

2022-04-14 22:25 UTC, cobbal requested changes
Looks pretty good overall. Some good cleanup in there. Few minor issues.

2022-04-14 22:25 UTC, cobbal commented on Sources/FishyJoesCSharpRuntime/File.swift
> +//  File.swift
File.swift

2022-04-14 22:25 UTC, cobbal commented on Sources/FishyJoesCore/FishyJoesContext.swift
> +    let cSharpTranslator = CSharpTranslator()
I don't like the duplicate translators.

2022-04-14 22:25 UTC, cobbal commented on Sources/FishyJoesCore/FishyJoesContext.swift
> +        seperator: Character = "."
typo: separator.

2022-04-14 22:25 UTC, cobbal commented on Sources/FishyJoesCore/FishyJoesContext.swift
> +                    fatalError()
The error message is important, as users may have forgotten an annotation

2022-04-14 22:25 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/Class.swift
> +protocol Class: _Class where InnerClass == Self {}
I hate this protocol name.

2022-04-14 22:25 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/Class.swift
> +protocol Class: _Class where InnerClass == Self {}
Maybe "NestedClass" would be better.

2022-04-14 22:25 UTC, cobbal commented on Sources/FishyJoesExecute/CodeGen.swift
> +    @Flag(name: .customLong("C#"), inversion: .prefixedNo, help: "Generate a C# Package")
"#" is usually a shell comment character, so I don't think we should use it in an option.

2022-04-14 22:25 UTC, cobbal commented on Sources/FishyJoesExecute/Platform.swift
> +            var cSharpPlatformBuildDirectory: String {
You can do local getters? nifty.

2022-04-14 22:26 UTC, cobbal commented on Sources/FishyJoesCore/FishyJoesContext.swift
> +    let cSharpTranslator = CSharpTranslator()
In fact, we should probably just create the translators up front, drop the init requirement, then stick them in an array.

2022-04-15 20:31 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/FishyJoesContext.swift
> +    let cSharpTranslator = CSharpTranslator()
Test comment from Xcode

2022-04-15 20:41 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/FishyJoesContext.swift
> +    let cSharpTranslator = CSharpTranslator()
Fixed.

2022-04-15 20:42 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/FishyJoesContext.swift
> +        seperator: Character = "."
Fixed.

2022-04-15 20:45 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/FishyJoesContext.swift
> +                    fatalError()
Fixed. Don't know how I lost that.

2022-04-15 20:45 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/Unparse/Class.swift
> +protocol Class: _Class where InnerClass == Self {}
Fixed.

2022-04-15 20:46 UTC, bscothern-Cricut commented on Sources/FishyJoesExecute/CodeGen.swift
> +    @Flag(name: .customLong("C#"), inversion: .prefixedNo, help: "Generate a C# Package")
Fixed.

2022-04-15 20:46 UTC, bscothern-Cricut commented on Sources/FishyJoesExecute/Platform.swift
> +            var cSharpPlatformBuildDirectory: String {
Yep, they are great.

2022-04-15 21:06 UTC, cobbal approved these changes
Looks good.

2022-04-15 21:11 UTC, merged