Cobbal/ts testing
cricut/FishyJoes pull request #59
Opened 2022-06-09 22:29 UTC by cobbal

2022-06-09 22:53 UTC, mstokercricut requested changes

2022-06-09 22:53 UTC, mstokercricut commented on integration-tests/TestAPI-bindings/node-test/TestAPI.test.ts
> +import { TestAPI } from 'TestAPI';
Now that this is not within that strange context, can these tests live in their own files? Each `// FooTests` comment indicates where test cases are broken (in the Kotlin tests, at least).

2022-06-10 00:46 UTC, cobbal commented on integration-tests/TestAPI-bindings/node-test/TestAPI.test.ts
> +import { TestAPI } from 'TestAPI';
They certainly can. Will fix tomorrow.

2022-06-10 14:07 UTC, kellyo-cricut commented on integration-tests/TestAPI-bindings/node-test/TestAPI.test.ts
> +import { TestAPI } from 'TestAPI';
another common approach to grouping these is using `describe` as a wrapper for a function and/or class, and having `it`/`test` blocks inside each.

```
describe('primitive values', () => {
  it('should correctly map numeric types', () => {
    expect(...)
  })
})

2022-06-10 14:08 UTC, kellyo-cricut approved these changes

2022-06-10 17:44 UTC, mstokercricut approved these changes

2022-06-13 20:08 UTC, merged