async/await
cricut/FishyJoes pull request #83
Opened 2022-11-21 18:22 UTC by bscothern-Cricut

2023-04-11 22:53 UTC, cobbal requested changes
Mostly minor stuff

2023-04-11 22:53 UTC, cobbal commented on Sources/FishyJoesCommonRuntime/Box.swift
> +    public func callAsFunction<Argument, Result>(_ arg: Argument) throws -> Result where T == (Argument) throws -> Result {
Can we put everything after == in parens?

2023-04-11 22:53 UTC, cobbal commented on Sources/FishyJoesCommonRuntime/Box.swift
> +    public func callAsFunction<Argument, Result>(_ arg: Argument) throws -> Result where T == (Argument) throws -> Result {
and here

2023-04-11 22:53 UTC, cobbal commented on Sources/FishyJoesCore/Translators/KotlinTranslate.swift
> +                returnType: !method.isAsync ? context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides).kotlinType : .void,
Flip the order, lose the negation

2023-04-11 22:53 UTC, cobbal commented on Sources/FishyJoesCore/Translators/NodeTranslate.swift
> +                argIndex = 0
Can this be made local? I don't like the idea of 2 loops using the same counter.

2023-04-11 22:53 UTC, cobbal commented on integration-tests/TestAPI-bindings/Package.swift
> +                .unsafeFlags(["-warn-concurrency"])
Should this also be added to the template in FishyJoesExecute?

2023-04-11 22:53 UTC, cobbal commented on Sources/FishyJoesCore/Unparse/SourceFragment.swift
> +        output(openingLine, newLineTerminated: !openingLine.isEmpty)
Is this used? I don't like it.

2023-04-11 22:53 UTC, cobbal commented on integration-tests/TestAPI-bindings/node-test/package.json
> +    "test-wasm": "node --inspect --experimental-vm-modules node_modules/jest/bin/jest.js --run-in-band --detect-open-handles --force-exit --debug --no-watchman -c jest.config.wasm.cjs",
probably shouldn't commit this

2023-04-12 15:59 UTC, bscothern-Cricut commented on Sources/FishyJoesCommonRuntime/Box.swift
> +    public func callAsFunction<Argument, Result>(_ arg: Argument) throws -> Result where T == (Argument) throws -> Result {
Done.

2023-04-12 16:01 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/Translators/KotlinTranslate.swift
> +                returnType: !method.isAsync ? context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides).kotlinType : .void,
Done. This should be temporary while moving to full async calls.

2023-04-12 16:02 UTC, bscothern-Cricut commented on integration-tests/TestAPI-bindings/Package.swift
> +                .unsafeFlags(["-warn-concurrency"])
Probably. We should discuss it but it makes sure we are taking note of how we are passing around data.

2023-04-12 16:05 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/Unparse/SourceFragment.swift
> +        output(openingLine, newLineTerminated: !openingLine.isEmpty)
It isn't being used anymore. It was an early aspect of how I was generating some stuff. I will remove it.

2023-04-12 16:05 UTC, bscothern-Cricut commented on integration-tests/TestAPI-bindings/node-test/package.json
> +    "test-wasm": "node --inspect --experimental-vm-modules node_modules/jest/bin/jest.js --run-in-band --detect-open-handles --force-exit --debug --no-watchman -c jest.config.wasm.cjs",
Good catch. Removed.

2023-04-12 16:07 UTC, bscothern-Cricut commented on Sources/FishyJoesCore/Translators/NodeTranslate.swift
> +                argIndex = 0
You use it for several things. I'll just change mine to be a local so the behavior in the other spots aren't changed.

2023-04-12 16:08 UTC, bscothern-Cricut commented on Sources/FishyJoesCommonRuntime/Box.swift
> +    public func callAsFunction<Argument, Result>(_ arg: Argument) throws -> Result where T == (Argument) throws -> Result {
Fixed.

2023-05-03 16:28 UTC, merged